// Proper sentences for the typing stream. One sentence is queued at a time and
// its words flow into the stream in order.
export const SENTENCES: string[] = [
  'The quick brown fox jumps over the lazy dog.',
  'A journey of a thousand miles begins with a single step.',
  'She sells seashells by the shore on sunny afternoons.',
  'Practice makes perfect when you show up every single day.',
  'The early bird catches the worm before the sun rises.',
  'Reading widely opens doors that money alone cannot buy.',
  'A gentle breeze carried the scent of rain across the fields.',
  'Curiosity is the engine that drives every great discovery.',
  'The best way to predict the future is to create it yourself.',
  'Kindness costs nothing yet it is worth more than gold.',
  'He packed his bags and boarded the train before dawn.',
  'The old library smelled of paper, dust, and quiet wonder.',
  'Small habits repeated daily shape the person you become.',
  'The river carved its path through the mountains for centuries.',
  'A good book is a friend that never asks for anything back.',
  'They laughed until their sides ached and the night grew cold.',
  'Patience and persistence quietly conquer almost every problem.',
  'The chef sliced the ripe tomatoes with a steady hand.',
  'Every sunset promises that tomorrow will bring a fresh start.',
  'Music has a way of saying what words never quite reach.',
  'The children built a sandcastle taller than they were.',
  'Honesty may be difficult, but it is always the shorter road.',
  'A single candle can light a room that darkness has claimed.',
  'The scientist recorded her results carefully in a worn notebook.',
  'Mountains teach us that the slow climb is worth the view.',
  'He whispered a secret that changed everything between them.',
  'Fresh bread and hot coffee make an ordinary morning feel rich.',
  'The garden bloomed in colors no painter could ever mix.',
  'Courage is not the absence of fear but action despite it.',
  'The city lights flickered like stars scattered across the ground.',
  'Learning a new language rewires the way you see the world.',
  'The dog waited by the door long after the car had gone.',
  'Great ideas often arrive quietly while you are doing the dishes.',
  'A warm smile is the universal language of quiet welcome.',
  'The waves rolled in slowly and erased the footprints on the sand.',
  'Time spent with good friends is never counted as wasted.',
  'The clock on the wall ticked louder as the deadline neared.',
  'She planted a tree whose shade she would never sit beneath.',
  'The mechanic fixed the engine with patience and a steady wrench.',
  'A clear mind makes room for solutions you could not see before.',
  'The storm passed and left the whole valley washed and green.',
  'Wisdom begins the moment you admit how little you truly know.',
  'The painter mixed blue and yellow to capture the summer grass.',
  'Every expert was once a beginner who refused to give up.',
  'The train rattled north through fields of gold and grey.',
  'A whispered kindness can outlast the loudest cruel word.',
  'The baker rose before the sun to knead the morning dough.',
  'Failure is simply feedback dressed in uncomfortable clothes.',
  'The stars appeared one by one as the campfire burned low.',
  'A tidy desk often hides a mind bursting with wild ideas.',
  'The teacher believed in the student before he believed in himself.',
  'Rain tapped the window while the kettle sang on the stove.',
  'Good design is invisible until you notice how easy it feels.',
  'The hikers reached the summit just as the fog began to lift.',
  'A promise kept quietly is worth more than a loud vow broken.',
  'The market buzzed with color, spices, and cheerful bargaining.',
  'She read the letter twice and then folded it against her heart.',
  'The bridge swayed gently as the travelers crossed the ravine.',
  'Every question you ask is a small act of brave curiosity.',
  'The cat stretched in the sunlight and yawned without a care.',
  'Hard work beats talent when talent forgets to work hard.',
  'The violinist closed her eyes and let the melody carry her.',
  'A map is useless until you decide where you truly want to go.',
  'The farmer watched the clouds and read the coming weather.',
  'Laughter shared across a table turns strangers into friends.',
  'The lighthouse swept the dark sea with its patient beam.',
  'He built the shelf himself and felt proud of every crooked nail.',
  'The answer lies not in speed but in the direction you choose.',
  'Snow fell softly and hushed the busy streets into stillness.',
  'A grateful heart notices the small gifts hidden in a plain day.',
  'The astronaut floated weightless above a blue and fragile earth.',
  'Words have weight, so choose the ones you carry with care.',
  'The puppy chased its tail in circles until it grew dizzy.',
  'Slow down enough and the ordinary reveals its quiet magic.',
  'The carpenter measured twice and cut the board just once.',
  'Friendship grows in the small moments no one thinks to count.',
  'The runner ignored the ache and pushed toward the final mile.',
  'A single honest apology can rebuild a bridge that pride burned.',
  'The moon rose full and painted the lake in liquid silver.',
  'Ideas are cheap, but the courage to build them is rare.',
  'The gardener pulled the weeds and thanked the stubborn soil.',
  'Every closed door hides a hallway you have not yet walked.',
  'The orchestra tuned together and the hall fell silent with hope.',
  'A cup of tea and a quiet hour can mend a tangled mind.',
  'The sailor trusted the compass when the fog swallowed the coast.',
  'Progress is often just failure that finally learned its lesson.',
  'The bakery window glowed warm against the cold morning street.',
  'She spoke softly, yet the whole room leaned in to listen.',
  'The bicycle wheels hummed along the quiet country lane.',
  'Small kindnesses ripple outward far beyond what you can see.',
  'The novelist wrote one honest page before the world woke up.',
  'A steady rhythm turns a hard task into a bearable song.',
  'The fox paused at the edge of the wood and studied the field.',
  'Gratitude turns what we have into more than enough.',
  'The blacksmith shaped the glowing iron with confident blows.',
  'Every mountain looks impossible until the first careful step.',
  'The rain finally stopped and the birds returned to the wire.',
  'A quiet mind hears answers that a noisy one always misses.',
  'The team celebrated a small win as if it were the whole season.',
  'Keep your promises small and your effort large, and you will grow.',
];
