// Country data for Where. Flag emoji are derived from the ISO code.

export interface Country {
  name: string;
  capital: string;
  code: string; // ISO 3166-1 alpha-2
}

/** Turn a 2-letter country code into its flag emoji. */
export function flagEmoji(code: string): string {
  return code
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65));
}

export const COUNTRIES: Country[] = [
  { name: 'Argentina', capital: 'Buenos Aires', code: 'AR' },
  { name: 'Australia', capital: 'Canberra', code: 'AU' },
  { name: 'Austria', capital: 'Vienna', code: 'AT' },
  { name: 'Belgium', capital: 'Brussels', code: 'BE' },
  { name: 'Brazil', capital: 'Brasília', code: 'BR' },
  { name: 'Canada', capital: 'Ottawa', code: 'CA' },
  { name: 'Chile', capital: 'Santiago', code: 'CL' },
  { name: 'China', capital: 'Beijing', code: 'CN' },
  { name: 'Colombia', capital: 'Bogotá', code: 'CO' },
  { name: 'Croatia', capital: 'Zagreb', code: 'HR' },
  { name: 'Czechia', capital: 'Prague', code: 'CZ' },
  { name: 'Denmark', capital: 'Copenhagen', code: 'DK' },
  { name: 'Egypt', capital: 'Cairo', code: 'EG' },
  { name: 'Finland', capital: 'Helsinki', code: 'FI' },
  { name: 'France', capital: 'Paris', code: 'FR' },
  { name: 'Germany', capital: 'Berlin', code: 'DE' },
  { name: 'Greece', capital: 'Athens', code: 'GR' },
  { name: 'Hungary', capital: 'Budapest', code: 'HU' },
  { name: 'Iceland', capital: 'Reykjavík', code: 'IS' },
  { name: 'India', capital: 'New Delhi', code: 'IN' },
  { name: 'Indonesia', capital: 'Jakarta', code: 'ID' },
  { name: 'Iran', capital: 'Tehran', code: 'IR' },
  { name: 'Iraq', capital: 'Baghdad', code: 'IQ' },
  { name: 'Ireland', capital: 'Dublin', code: 'IE' },
  { name: 'Israel', capital: 'Jerusalem', code: 'IL' },
  { name: 'Italy', capital: 'Rome', code: 'IT' },
  { name: 'Japan', capital: 'Tokyo', code: 'JP' },
  { name: 'Kenya', capital: 'Nairobi', code: 'KE' },
  { name: 'Malaysia', capital: 'Kuala Lumpur', code: 'MY' },
  { name: 'Mexico', capital: 'Mexico City', code: 'MX' },
  { name: 'Morocco', capital: 'Rabat', code: 'MA' },
  { name: 'Netherlands', capital: 'Amsterdam', code: 'NL' },
  { name: 'New Zealand', capital: 'Wellington', code: 'NZ' },
  { name: 'Nigeria', capital: 'Abuja', code: 'NG' },
  { name: 'Norway', capital: 'Oslo', code: 'NO' },
  { name: 'Peru', capital: 'Lima', code: 'PE' },
  { name: 'Philippines', capital: 'Manila', code: 'PH' },
  { name: 'Poland', capital: 'Warsaw', code: 'PL' },
  { name: 'Portugal', capital: 'Lisbon', code: 'PT' },
  { name: 'Romania', capital: 'Bucharest', code: 'RO' },
  { name: 'Russia', capital: 'Moscow', code: 'RU' },
  { name: 'Saudi Arabia', capital: 'Riyadh', code: 'SA' },
  { name: 'Singapore', capital: 'Singapore', code: 'SG' },
  { name: 'South Africa', capital: 'Pretoria', code: 'ZA' },
  { name: 'South Korea', capital: 'Seoul', code: 'KR' },
  { name: 'Spain', capital: 'Madrid', code: 'ES' },
  { name: 'Sweden', capital: 'Stockholm', code: 'SE' },
  { name: 'Switzerland', capital: 'Bern', code: 'CH' },
  { name: 'Thailand', capital: 'Bangkok', code: 'TH' },
  { name: 'Turkey', capital: 'Ankara', code: 'TR' },
  { name: 'Ukraine', capital: 'Kyiv', code: 'UA' },
  { name: 'United Kingdom', capital: 'London', code: 'GB' },
  { name: 'United States', capital: 'Washington', code: 'US' },
  { name: 'Vietnam', capital: 'Hanoi', code: 'VN' },
  { name: 'Kazakhstan', capital: 'Astana', code: 'KZ' },
  { name: 'Pakistan', capital: 'Islamabad', code: 'PK' },
  { name: 'Bangladesh', capital: 'Dhaka', code: 'BD' },
  { name: 'Cuba', capital: 'Havana', code: 'CU' },
  { name: 'Ethiopia', capital: 'Addis Ababa', code: 'ET' },
  { name: 'Ghana', capital: 'Accra', code: 'GH' },
  { name: 'United Arab Emirates', capital: 'Abu Dhabi', code: 'AE' },
  { name: 'Qatar', capital: 'Doha', code: 'QA' },
  { name: 'Jordan', capital: 'Amman', code: 'JO' },
  { name: 'Lebanon', capital: 'Beirut', code: 'LB' },
  { name: 'Nepal', capital: 'Kathmandu', code: 'NP' },
  { name: 'Myanmar', capital: 'Naypyidaw', code: 'MM' },
  { name: 'Cambodia', capital: 'Phnom Penh', code: 'KH' },
  { name: 'Ecuador', capital: 'Quito', code: 'EC' },
  { name: 'Venezuela', capital: 'Caracas', code: 'VE' },
  { name: 'Uruguay', capital: 'Montevideo', code: 'UY' },
  { name: 'Tunisia', capital: 'Tunis', code: 'TN' },
  { name: 'Algeria', capital: 'Algiers', code: 'DZ' },
  { name: 'Tanzania', capital: 'Dodoma', code: 'TZ' },
  { name: 'Uganda', capital: 'Kampala', code: 'UG' },
  { name: 'Zimbabwe', capital: 'Harare', code: 'ZW' },
  { name: 'Serbia', capital: 'Belgrade', code: 'RS' },
  { name: 'Slovakia', capital: 'Bratislava', code: 'SK' },
  { name: 'Slovenia', capital: 'Ljubljana', code: 'SI' },
  { name: 'Bulgaria', capital: 'Sofia', code: 'BG' },
  { name: 'Estonia', capital: 'Tallinn', code: 'EE' },
  { name: 'Latvia', capital: 'Riga', code: 'LV' },
  { name: 'Lithuania', capital: 'Vilnius', code: 'LT' },
];
