// Country data for Where. Flag emoji are derived from the ISO 3166-1 alpha-2
// code (two regional-indicator letters). Every code below is an official ISO
// code, so each has a standard Unicode flag emoji. (Note: some platforms —
// e.g. Chrome on Windows — render these as the two letters rather than a flag.)

export interface Country {
  name: string;
  capital: string;
  code: string; // ISO 3166-1 alpha-2
}

/** Turn a 2-letter country code into its flag emoji. */
export function flagEmoji(code: string): string {
  return code
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65));
}

export const COUNTRIES: Country[] = [
  { name: 'Afghanistan', capital: 'Kabul', code: 'AF' },
  { name: 'Albania', capital: 'Tirana', code: 'AL' },
  { name: 'Algeria', capital: 'Algiers', code: 'DZ' },
  { name: 'Andorra', capital: 'Andorra la Vella', code: 'AD' },
  { name: 'Angola', capital: 'Luanda', code: 'AO' },
  { name: 'Antigua and Barbuda', capital: "Saint John's", code: 'AG' },
  { name: 'Argentina', capital: 'Buenos Aires', code: 'AR' },
  { name: 'Armenia', capital: 'Yerevan', code: 'AM' },
  { name: 'Australia', capital: 'Canberra', code: 'AU' },
  { name: 'Austria', capital: 'Vienna', code: 'AT' },
  { name: 'Azerbaijan', capital: 'Baku', code: 'AZ' },
  { name: 'Bahamas', capital: 'Nassau', code: 'BS' },
  { name: 'Bahrain', capital: 'Manama', code: 'BH' },
  { name: 'Bangladesh', capital: 'Dhaka', code: 'BD' },
  { name: 'Barbados', capital: 'Bridgetown', code: 'BB' },
  { name: 'Belarus', capital: 'Minsk', code: 'BY' },
  { name: 'Belgium', capital: 'Brussels', code: 'BE' },
  { name: 'Belize', capital: 'Belmopan', code: 'BZ' },
  { name: 'Benin', capital: 'Porto-Novo', code: 'BJ' },
  { name: 'Bhutan', capital: 'Thimphu', code: 'BT' },
  { name: 'Bolivia', capital: 'Sucre', code: 'BO' },
  { name: 'Bosnia and Herzegovina', capital: 'Sarajevo', code: 'BA' },
  { name: 'Botswana', capital: 'Gaborone', code: 'BW' },
  { name: 'Brazil', capital: 'Brasília', code: 'BR' },
  { name: 'Brunei', capital: 'Bandar Seri Begawan', code: 'BN' },
  { name: 'Bulgaria', capital: 'Sofia', code: 'BG' },
  { name: 'Burkina Faso', capital: 'Ouagadougou', code: 'BF' },
  { name: 'Burundi', capital: 'Gitega', code: 'BI' },
  { name: 'Cambodia', capital: 'Phnom Penh', code: 'KH' },
  { name: 'Cameroon', capital: 'Yaoundé', code: 'CM' },
  { name: 'Canada', capital: 'Ottawa', code: 'CA' },
  { name: 'Cape Verde', capital: 'Praia', code: 'CV' },
  { name: 'Central African Republic', capital: 'Bangui', code: 'CF' },
  { name: 'Chad', capital: "N'Djamena", code: 'TD' },
  { name: 'Chile', capital: 'Santiago', code: 'CL' },
  { name: 'China', capital: 'Beijing', code: 'CN' },
  { name: 'Colombia', capital: 'Bogotá', code: 'CO' },
  { name: 'Comoros', capital: 'Moroni', code: 'KM' },
  { name: 'Congo', capital: 'Brazzaville', code: 'CG' },
  { name: 'Costa Rica', capital: 'San José', code: 'CR' },
  { name: 'Croatia', capital: 'Zagreb', code: 'HR' },
  { name: 'Cuba', capital: 'Havana', code: 'CU' },
  { name: 'Cyprus', capital: 'Nicosia', code: 'CY' },
  { name: 'Czechia', capital: 'Prague', code: 'CZ' },
  { name: 'DR Congo', capital: 'Kinshasa', code: 'CD' },
  { name: 'Denmark', capital: 'Copenhagen', code: 'DK' },
  { name: 'Djibouti', capital: 'Djibouti', code: 'DJ' },
  { name: 'Dominica', capital: 'Roseau', code: 'DM' },
  { name: 'Dominican Republic', capital: 'Santo Domingo', code: 'DO' },
  { name: 'Ecuador', capital: 'Quito', code: 'EC' },
  { name: 'Egypt', capital: 'Cairo', code: 'EG' },
  { name: 'El Salvador', capital: 'San Salvador', code: 'SV' },
  { name: 'Equatorial Guinea', capital: 'Malabo', code: 'GQ' },
  { name: 'Eritrea', capital: 'Asmara', code: 'ER' },
  { name: 'Estonia', capital: 'Tallinn', code: 'EE' },
  { name: 'Eswatini', capital: 'Mbabane', code: 'SZ' },
  { name: 'Ethiopia', capital: 'Addis Ababa', code: 'ET' },
  { name: 'Fiji', capital: 'Suva', code: 'FJ' },
  { name: 'Finland', capital: 'Helsinki', code: 'FI' },
  { name: 'France', capital: 'Paris', code: 'FR' },
  { name: 'Gabon', capital: 'Libreville', code: 'GA' },
  { name: 'Gambia', capital: 'Banjul', code: 'GM' },
  { name: 'Georgia', capital: 'Tbilisi', code: 'GE' },
  { name: 'Germany', capital: 'Berlin', code: 'DE' },
  { name: 'Ghana', capital: 'Accra', code: 'GH' },
  { name: 'Greece', capital: 'Athens', code: 'GR' },
  { name: 'Grenada', capital: "Saint George's", code: 'GD' },
  { name: 'Guatemala', capital: 'Guatemala City', code: 'GT' },
  { name: 'Guinea', capital: 'Conakry', code: 'GN' },
  { name: 'Guinea-Bissau', capital: 'Bissau', code: 'GW' },
  { name: 'Guyana', capital: 'Georgetown', code: 'GY' },
  { name: 'Haiti', capital: 'Port-au-Prince', code: 'HT' },
  { name: 'Honduras', capital: 'Tegucigalpa', code: 'HN' },
  { name: 'Hungary', capital: 'Budapest', code: 'HU' },
  { name: 'Iceland', capital: 'Reykjavík', code: 'IS' },
  { name: 'India', capital: 'New Delhi', code: 'IN' },
  { name: 'Indonesia', capital: 'Jakarta', code: 'ID' },
  { name: 'Iran', capital: 'Tehran', code: 'IR' },
  { name: 'Iraq', capital: 'Baghdad', code: 'IQ' },
  { name: 'Ireland', capital: 'Dublin', code: 'IE' },
  { name: 'Israel', capital: 'Jerusalem', code: 'IL' },
  { name: 'Italy', capital: 'Rome', code: 'IT' },
  { name: 'Ivory Coast', capital: 'Yamoussoukro', code: 'CI' },
  { name: 'Jamaica', capital: 'Kingston', code: 'JM' },
  { name: 'Japan', capital: 'Tokyo', code: 'JP' },
  { name: 'Jordan', capital: 'Amman', code: 'JO' },
  { name: 'Kazakhstan', capital: 'Astana', code: 'KZ' },
  { name: 'Kenya', capital: 'Nairobi', code: 'KE' },
  { name: 'Kiribati', capital: 'Tarawa', code: 'KI' },
  { name: 'Kuwait', capital: 'Kuwait City', code: 'KW' },
  { name: 'Kyrgyzstan', capital: 'Bishkek', code: 'KG' },
  { name: 'Laos', capital: 'Vientiane', code: 'LA' },
  { name: 'Latvia', capital: 'Riga', code: 'LV' },
  { name: 'Lebanon', capital: 'Beirut', code: 'LB' },
  { name: 'Lesotho', capital: 'Maseru', code: 'LS' },
  { name: 'Liberia', capital: 'Monrovia', code: 'LR' },
  { name: 'Libya', capital: 'Tripoli', code: 'LY' },
  { name: 'Liechtenstein', capital: 'Vaduz', code: 'LI' },
  { name: 'Lithuania', capital: 'Vilnius', code: 'LT' },
  { name: 'Luxembourg', capital: 'Luxembourg', code: 'LU' },
  { name: 'Madagascar', capital: 'Antananarivo', code: 'MG' },
  { name: 'Malawi', capital: 'Lilongwe', code: 'MW' },
  { name: 'Malaysia', capital: 'Kuala Lumpur', code: 'MY' },
  { name: 'Maldives', capital: 'Malé', code: 'MV' },
  { name: 'Mali', capital: 'Bamako', code: 'ML' },
  { name: 'Malta', capital: 'Valletta', code: 'MT' },
  { name: 'Marshall Islands', capital: 'Majuro', code: 'MH' },
  { name: 'Mauritania', capital: 'Nouakchott', code: 'MR' },
  { name: 'Mauritius', capital: 'Port Louis', code: 'MU' },
  { name: 'Mexico', capital: 'Mexico City', code: 'MX' },
  { name: 'Micronesia', capital: 'Palikir', code: 'FM' },
  { name: 'Moldova', capital: 'Chișinău', code: 'MD' },
  { name: 'Monaco', capital: 'Monaco', code: 'MC' },
  { name: 'Mongolia', capital: 'Ulaanbaatar', code: 'MN' },
  { name: 'Montenegro', capital: 'Podgorica', code: 'ME' },
  { name: 'Morocco', capital: 'Rabat', code: 'MA' },
  { name: 'Mozambique', capital: 'Maputo', code: 'MZ' },
  { name: 'Myanmar', capital: 'Naypyidaw', code: 'MM' },
  { name: 'Namibia', capital: 'Windhoek', code: 'NA' },
  { name: 'Nauru', capital: 'Yaren', code: 'NR' },
  { name: 'Nepal', capital: 'Kathmandu', code: 'NP' },
  { name: 'Netherlands', capital: 'Amsterdam', code: 'NL' },
  { name: 'New Zealand', capital: 'Wellington', code: 'NZ' },
  { name: 'Nicaragua', capital: 'Managua', code: 'NI' },
  { name: 'Niger', capital: 'Niamey', code: 'NE' },
  { name: 'Nigeria', capital: 'Abuja', code: 'NG' },
  { name: 'North Korea', capital: 'Pyongyang', code: 'KP' },
  { name: 'North Macedonia', capital: 'Skopje', code: 'MK' },
  { name: 'Norway', capital: 'Oslo', code: 'NO' },
  { name: 'Oman', capital: 'Muscat', code: 'OM' },
  { name: 'Pakistan', capital: 'Islamabad', code: 'PK' },
  { name: 'Palau', capital: 'Ngerulmud', code: 'PW' },
  { name: 'Palestine', capital: 'Ramallah', code: 'PS' },
  { name: 'Panama', capital: 'Panama City', code: 'PA' },
  { name: 'Papua New Guinea', capital: 'Port Moresby', code: 'PG' },
  { name: 'Paraguay', capital: 'Asunción', code: 'PY' },
  { name: 'Peru', capital: 'Lima', code: 'PE' },
  { name: 'Philippines', capital: 'Manila', code: 'PH' },
  { name: 'Poland', capital: 'Warsaw', code: 'PL' },
  { name: 'Portugal', capital: 'Lisbon', code: 'PT' },
  { name: 'Qatar', capital: 'Doha', code: 'QA' },
  { name: 'Romania', capital: 'Bucharest', code: 'RO' },
  { name: 'Russia', capital: 'Moscow', code: 'RU' },
  { name: 'Rwanda', capital: 'Kigali', code: 'RW' },
  { name: 'Saint Kitts and Nevis', capital: 'Basseterre', code: 'KN' },
  { name: 'Saint Lucia', capital: 'Castries', code: 'LC' },
  { name: 'Saint Vincent and the Grenadines', capital: 'Kingstown', code: 'VC' },
  { name: 'Samoa', capital: 'Apia', code: 'WS' },
  { name: 'San Marino', capital: 'San Marino', code: 'SM' },
  { name: 'Sao Tome and Principe', capital: 'São Tomé', code: 'ST' },
  { name: 'Saudi Arabia', capital: 'Riyadh', code: 'SA' },
  { name: 'Senegal', capital: 'Dakar', code: 'SN' },
  { name: 'Serbia', capital: 'Belgrade', code: 'RS' },
  { name: 'Seychelles', capital: 'Victoria', code: 'SC' },
  { name: 'Sierra Leone', capital: 'Freetown', code: 'SL' },
  { name: 'Singapore', capital: 'Singapore', code: 'SG' },
  { name: 'Slovakia', capital: 'Bratislava', code: 'SK' },
  { name: 'Slovenia', capital: 'Ljubljana', code: 'SI' },
  { name: 'Solomon Islands', capital: 'Honiara', code: 'SB' },
  { name: 'Somalia', capital: 'Mogadishu', code: 'SO' },
  { name: 'South Africa', capital: 'Pretoria', code: 'ZA' },
  { name: 'South Korea', capital: 'Seoul', code: 'KR' },
  { name: 'South Sudan', capital: 'Juba', code: 'SS' },
  { name: 'Spain', capital: 'Madrid', code: 'ES' },
  { name: 'Sri Lanka', capital: 'Sri Jayawardenepura Kotte', code: 'LK' },
  { name: 'Sudan', capital: 'Khartoum', code: 'SD' },
  { name: 'Suriname', capital: 'Paramaribo', code: 'SR' },
  { name: 'Sweden', capital: 'Stockholm', code: 'SE' },
  { name: 'Switzerland', capital: 'Bern', code: 'CH' },
  { name: 'Syria', capital: 'Damascus', code: 'SY' },
  { name: 'Taiwan', capital: 'Taipei', code: 'TW' },
  { name: 'Tajikistan', capital: 'Dushanbe', code: 'TJ' },
  { name: 'Tanzania', capital: 'Dodoma', code: 'TZ' },
  { name: 'Thailand', capital: 'Bangkok', code: 'TH' },
  { name: 'Timor-Leste', capital: 'Dili', code: 'TL' },
  { name: 'Togo', capital: 'Lomé', code: 'TG' },
  { name: 'Tonga', capital: "Nuku'alofa", code: 'TO' },
  { name: 'Trinidad and Tobago', capital: 'Port of Spain', code: 'TT' },
  { name: 'Tunisia', capital: 'Tunis', code: 'TN' },
  { name: 'Turkey', capital: 'Ankara', code: 'TR' },
  { name: 'Turkmenistan', capital: 'Ashgabat', code: 'TM' },
  { name: 'Tuvalu', capital: 'Funafuti', code: 'TV' },
  { name: 'Uganda', capital: 'Kampala', code: 'UG' },
  { name: 'Ukraine', capital: 'Kyiv', code: 'UA' },
  { name: 'United Arab Emirates', capital: 'Abu Dhabi', code: 'AE' },
  { name: 'United Kingdom', capital: 'London', code: 'GB' },
  { name: 'United States', capital: 'Washington', code: 'US' },
  { name: 'Uruguay', capital: 'Montevideo', code: 'UY' },
  { name: 'Uzbekistan', capital: 'Tashkent', code: 'UZ' },
  { name: 'Vanuatu', capital: 'Port Vila', code: 'VU' },
  { name: 'Vatican City', capital: 'Vatican City', code: 'VA' },
  { name: 'Venezuela', capital: 'Caracas', code: 'VE' },
  { name: 'Vietnam', capital: 'Hanoi', code: 'VN' },
  { name: 'Yemen', capital: "Sana'a", code: 'YE' },
  { name: 'Zambia', capital: 'Lusaka', code: 'ZM' },
  { name: 'Zimbabwe', capital: 'Harare', code: 'ZW' },
];

export type Difficulty = 'easy' | 'hard';

// The ~100 most globally recognisable countries make up the "easy" pool; every
// other country falls into "hard". Codes only, so the split survives edits to
// names/capitals above.
const FAMOUS_CODES = new Set<string>([
  'US', 'GB', 'FR', 'DE', 'IT', 'ES', 'PT', 'NL', 'BE', 'CH',
  'AT', 'IE', 'SE', 'NO', 'DK', 'FI', 'IS', 'PL', 'CZ', 'HU',
  'GR', 'RO', 'RU', 'UA', 'HR', 'RS', 'BG', 'SK', 'SI', 'LU',
  'MC', 'VA', 'MT', 'CY', 'CA', 'MX', 'BR', 'AR', 'CL', 'CO',
  'PE', 'VE', 'EC', 'BO', 'UY', 'PY', 'CU', 'JM', 'HT', 'CR',
  'PA', 'GT', 'CN', 'JP', 'KR', 'KP', 'IN', 'PK', 'BD', 'LK',
  'NP', 'TH', 'VN', 'MY', 'SG', 'ID', 'PH', 'MM', 'KH', 'TW',
  'MN', 'AF', 'TR', 'SA', 'AE', 'QA', 'KW', 'IL', 'IR', 'IQ',
  'JO', 'LB', 'SY', 'YE', 'OM', 'EG', 'ZA', 'NG', 'KE', 'ET',
  'MA', 'DZ', 'TN', 'GH', 'LY', 'ZW', 'AU', 'NZ', 'KZ', 'UZ',
]);

/** The famous, easier-to-recognise countries. */
export const EASY_COUNTRIES: Country[] = COUNTRIES.filter((c) => FAMOUS_CODES.has(c.code));
/** The remaining, lesser-known countries. */
export const HARD_COUNTRIES: Country[] = COUNTRIES.filter((c) => !FAMOUS_CODES.has(c.code));

/** The country pool for a difficulty. */
export function countriesFor(difficulty: Difficulty): Country[] {
  return difficulty === 'easy' ? EASY_COUNTRIES : HARD_COUNTRIES;
}
