// Curated bank of interesting words. Definitions and example sentences are written
// for this app; origins are brief factual etymologies.

export interface Word {
  word: string;
  say: string; // readable pronunciation respelling
  pos: string; // part of speech
  definition: string;
  examples: string[];
  synonyms: string[];
  origin: string;
}

export const WORDS: Word[] = [
  {
    word: 'petrichor',
    say: 'PET-ri-kor',
    pos: 'noun',
    definition: 'The earthy, pleasant smell produced when rain falls on dry soil.',
    examples: [
      'The first monsoon shower filled the streets with petrichor.',
      'She opened the window just to breathe in the petrichor.',
    ],
    synonyms: ['rain scent', 'earthy aroma'],
    origin: 'Greek petra “stone” + ichor, the fluid said to flow in the veins of the gods.',
  },
  {
    word: 'ephemeral',
    say: 'ih-FEM-er-uhl',
    pos: 'adjective',
    definition: 'Lasting for a very short time; fleeting.',
    examples: [
      'Fireflies give off an ephemeral glow that fades in seconds.',
      'Fame can be surprisingly ephemeral.',
    ],
    synonyms: ['fleeting', 'transient', 'momentary'],
    origin: 'Greek ephēmeros “lasting only a day”.',
  },
  {
    word: 'serendipity',
    say: 'ser-uhn-DIP-ih-tee',
    pos: 'noun',
    definition: 'The occurrence of happy or useful things by chance rather than design.',
    examples: [
      'Finding that book was pure serendipity.',
      'Their meeting was a moment of serendipity that changed both their lives.',
    ],
    synonyms: ['chance', 'fluke', 'fortune'],
    origin: 'Coined by Horace Walpole in 1754 after the fairy tale “The Three Princes of Serendip”.',
  },
  {
    word: 'mellifluous',
    say: 'muh-LIF-loo-uhs',
    pos: 'adjective',
    definition: 'Sweet and smooth to listen to; pleasingly musical.',
    examples: [
      'The narrator had a deep, mellifluous voice.',
      'A mellifluous melody drifted from the café.',
    ],
    synonyms: ['dulcet', 'honeyed', 'euphonious'],
    origin: 'Latin mel “honey” + fluere “to flow”.',
  },
  {
    word: 'ineffable',
    say: 'in-EF-uh-buhl',
    pos: 'adjective',
    definition: 'Too great or beautiful to be expressed in words.',
    examples: [
      'The view from the summit was ineffable.',
      'She felt an ineffable joy holding her newborn.',
    ],
    synonyms: ['indescribable', 'inexpressible', 'unutterable'],
    origin: 'Latin in- “not” + effabilis “able to be spoken”.',
  },
  {
    word: 'sonder',
    say: 'SON-der',
    pos: 'noun',
    definition:
      'The realization that every passerby is living a life as vivid and complex as your own.',
    examples: [
      'A wave of sonder hit her on the crowded platform.',
      'Sonder makes a busy street feel a little less lonely.',
    ],
    synonyms: ['empathy', 'awareness'],
    origin: 'A modern coinage from “The Dictionary of Obscure Sorrows” (2012).',
  },
  {
    word: 'quixotic',
    say: 'kwik-SOT-ik',
    pos: 'adjective',
    definition: 'Wildly idealistic and impractical; chasing lofty but unreachable goals.',
    examples: [
      'His quixotic plan to sail around the world in a rowboat worried his friends.',
      'It was a quixotic quest, but a noble one.',
    ],
    synonyms: ['idealistic', 'unrealistic', 'starry-eyed'],
    origin: 'After Don Quixote, the dreamer-hero of Cervantes’ novel.',
  },
  {
    word: 'ebullient',
    say: 'ih-BULL-yuhnt',
    pos: 'adjective',
    definition: 'Cheerful, enthusiastic, and full of energy.',
    examples: [
      'She gave an ebullient speech that lifted the whole room.',
      'The puppy was ebullient the moment its owner walked in.',
    ],
    synonyms: ['exuberant', 'buoyant', 'effervescent'],
    origin: 'Latin ebullire “to boil up”.',
  },
  {
    word: 'halcyon',
    say: 'HAL-see-uhn',
    pos: 'adjective',
    definition: 'Denoting a past time that was idyllically happy and peaceful.',
    examples: [
      'They spoke of the halcyon days of their youth.',
      'It was a halcyon summer none of them would forget.',
    ],
    synonyms: ['golden', 'serene', 'carefree'],
    origin: 'From the halcyon, a mythical bird said to calm the seas.',
  },
  {
    word: 'susurrus',
    say: 'soo-SUR-uhs',
    pos: 'noun',
    definition: 'A soft whispering or rustling sound.',
    examples: [
      'A susurrus of leaves followed the evening breeze.',
      'The library held only the susurrus of turning pages.',
    ],
    synonyms: ['whisper', 'murmur', 'rustle'],
    origin: 'Latin susurrus “a humming, muttering”.',
  },
  {
    word: 'nebulous',
    say: 'NEB-yuh-luhs',
    pos: 'adjective',
    definition: 'Vague, hazy, or hard to define.',
    examples: [
      'His plans for the future were still nebulous.',
      'The idea was exciting but nebulous.',
    ],
    synonyms: ['vague', 'hazy', 'unclear'],
    origin: 'Latin nebula “mist, cloud”.',
  },
  {
    word: 'cacophony',
    say: 'kuh-KOF-uh-nee',
    pos: 'noun',
    definition: 'A harsh, jarring mixture of sounds.',
    examples: [
      'The market was a cacophony of horns and shouting.',
      'Their first rehearsal was pure cacophony.',
    ],
    synonyms: ['din', 'racket', 'discord'],
    origin: 'Greek kakos “bad” + phōnē “sound”.',
  },
  {
    word: 'labyrinthine',
    say: 'lab-uh-RIN-thine',
    pos: 'adjective',
    definition: 'Twisting, intricate, and confusing, like a maze.',
    examples: [
      'The old city had labyrinthine alleys.',
      'He got lost in the labyrinthine rules of the contract.',
    ],
    synonyms: ['maze-like', 'tangled', 'convoluted'],
    origin: 'From the Labyrinth built for the Minotaur in Greek myth.',
  },
  {
    word: 'incandescent',
    say: 'in-kan-DES-uhnt',
    pos: 'adjective',
    definition: 'Glowing with heat and light; also, intensely passionate.',
    examples: [
      'The incandescent filament lit the room with a warm glow.',
      'She gave an incandescent performance.',
    ],
    synonyms: ['glowing', 'radiant', 'blazing'],
    origin: 'Latin incandescere “to glow with heat”.',
  },
  {
    word: 'verdant',
    say: 'VUR-dnt',
    pos: 'adjective',
    definition: 'Green and lush with growing plants.',
    examples: [
      'Rolling verdant hills stretched to the horizon.',
      'After the rains, the valley turned verdant.',
    ],
    synonyms: ['lush', 'green', 'leafy'],
    origin: 'Old French verdoyant “becoming green”.',
  },
  {
    word: 'reverie',
    say: 'REV-uh-ree',
    pos: 'noun',
    definition: 'A state of being pleasantly lost in one’s thoughts; a daydream.',
    examples: [
      'The train ride sent him into a long reverie.',
      'She was startled out of her reverie by the doorbell.',
    ],
    synonyms: ['daydream', 'trance', 'musing'],
    origin: 'French rêverie “dreaming”.',
  },
  {
    word: 'panacea',
    say: 'pan-uh-SEE-uh',
    pos: 'noun',
    definition: 'A supposed cure or solution for all problems.',
    examples: [
      'Technology is not a panacea for every social ill.',
      'They marketed the tonic as a panacea.',
    ],
    synonyms: ['cure-all', 'remedy', 'elixir'],
    origin: 'Greek panakeia “all-healing”.',
  },
  {
    word: 'zeitgeist',
    say: 'TSYTE-guyst',
    pos: 'noun',
    definition: 'The defining spirit, mood, or ideas of a particular period.',
    examples: [
      'The film captured the zeitgeist of the nineties.',
      'Memes are a window into the internet’s zeitgeist.',
    ],
    synonyms: ['spirit of the age', 'mood', 'ethos'],
    origin: 'German Zeit “time” + Geist “spirit”.',
  },
  {
    word: 'ethereal',
    say: 'ih-THEER-ee-uhl',
    pos: 'adjective',
    definition: 'Delicate and light in a way that seems too perfect for this world.',
    examples: [
      'The dancer moved with ethereal grace.',
      'Mist gave the forest an ethereal glow.',
    ],
    synonyms: ['delicate', 'airy', 'celestial'],
    origin: 'Greek aithēr “upper, purer air”.',
  },
  {
    word: 'gossamer',
    say: 'GOSS-uh-mer',
    pos: 'noun',
    definition: 'Something extremely light, thin, and delicate.',
    examples: [
      'The dress was made of gossamer silk.',
      'Dew clung to a gossamer of spider silk.',
    ],
    synonyms: ['filament', 'cobweb', 'wisp'],
    origin: 'Middle English, probably “goose summer”, the time when fine cobwebs appear.',
  },
  {
    word: 'effervescent',
    say: 'ef-er-VES-uhnt',
    pos: 'adjective',
    definition: 'Bubbly and lively; full of cheerful energy.',
    examples: [
      'Her effervescent personality made her easy to like.',
      'The drink was cold and effervescent.',
    ],
    synonyms: ['bubbly', 'vivacious', 'sparkling'],
    origin: 'Latin effervescere “to boil up”.',
  },
  {
    word: 'sesquipedalian',
    say: 'ses-kwih-puh-DAY-lee-uhn',
    pos: 'adjective',
    definition: 'Given to using long words; (of a word) having many syllables.',
    examples: [
      'His sesquipedalian prose sent readers reaching for a dictionary.',
      'She teased him for his sesquipedalian style of speaking.',
    ],
    synonyms: ['long-winded', 'polysyllabic', 'grandiloquent'],
    origin: 'Latin sesquipedalis “a foot and a half long”.',
  },
  {
    word: 'obfuscate',
    say: 'OB-fuh-skayt',
    pos: 'verb',
    definition: 'To deliberately make something unclear or hard to understand.',
    examples: [
      'The report seemed designed to obfuscate rather than inform.',
      'He tried to obfuscate the numbers with technical jargon.',
    ],
    synonyms: ['obscure', 'muddle', 'confuse'],
    origin: 'Latin obfuscare “to darken”.',
  },
  {
    word: 'perspicacious',
    say: 'pur-spih-KAY-shuhs',
    pos: 'adjective',
    definition: 'Having a ready insight into and understanding of things; keenly perceptive.',
    examples: [
      'A perspicacious editor spotted the flaw at once.',
      'Her perspicacious questions cut straight to the truth.',
    ],
    synonyms: ['astute', 'shrewd', 'discerning'],
    origin: 'Latin perspicax “sharp-sighted”.',
  },
  {
    word: 'obstreperous',
    say: 'uhb-STREP-er-uhs',
    pos: 'adjective',
    definition: 'Noisy and difficult to control; unruly.',
    examples: [
      'The obstreperous crowd refused to quiet down.',
      'An obstreperous toddler upended the whole dinner.',
    ],
    synonyms: ['unruly', 'boisterous', 'rowdy'],
    origin: 'Latin obstreperus “clamorous”, from ob- “against” + strepere “to make a noise”.',
  },
  {
    word: 'pusillanimous',
    say: 'pyoo-sih-LAN-ih-muhs',
    pos: 'adjective',
    definition: 'Showing a lack of courage or determination; timid.',
    examples: [
      'It was a pusillanimous decision to abandon the plan.',
      'He was too pusillanimous to voice his real opinion.',
    ],
    synonyms: ['timid', 'cowardly', 'faint-hearted'],
    origin: 'Latin pusillus “very small” + animus “mind, spirit”.',
  },
  {
    word: 'defenestration',
    say: 'dee-fen-uh-STRAY-shuhn',
    pos: 'noun',
    definition: 'The act of throwing someone or something out of a window.',
    examples: [
      'The uprising began with the famous defenestration of two officials.',
      'He joked that the printer deserved a swift defenestration.',
    ],
    synonyms: ['ejection', 'ousting'],
    origin: 'Latin de- “down from” + fenestra “window”.',
  },
  {
    word: 'sycophant',
    say: 'SIK-uh-fant',
    pos: 'noun',
    definition: 'A person who flatters powerful people to gain advantage.',
    examples: [
      'The king was surrounded by sycophants who agreed with everything.',
      'No one trusted the sycophant angling for a promotion.',
    ],
    synonyms: ['flatterer', 'toady', 'bootlicker'],
    origin: 'Greek sykophantēs “informer”, literally “fig-shower”.',
  },
  {
    word: 'lugubrious',
    say: 'luh-GOO-bree-uhs',
    pos: 'adjective',
    definition: 'Looking or sounding sad and dismal, often exaggeratedly so.',
    examples: [
      'He answered in a lugubrious tone that made everyone gloomier.',
      'The hound had a wonderfully lugubrious expression.',
    ],
    synonyms: ['mournful', 'doleful', 'gloomy'],
    origin: 'Latin lugubris “mournful”, from lugere “to mourn”.',
  },
  {
    word: 'recalcitrant',
    say: 'rih-KAL-sih-truhnt',
    pos: 'adjective',
    definition: 'Stubbornly resistant to authority or control.',
    examples: [
      'A recalcitrant witness refused to answer any questions.',
      'The recalcitrant engine would not start no matter what.',
    ],
    synonyms: ['obstinate', 'defiant', 'unruly'],
    origin: 'Latin recalcitrare “to kick back”, from calx “heel”.',
  },
  {
    word: 'grandiloquent',
    say: 'gran-DIL-uh-kwuhnt',
    pos: 'adjective',
    definition: 'Using pompous or extravagant language to impress.',
    examples: [
      'The speech was grandiloquent but said very little.',
      'He made a grandiloquent promise he could never keep.',
    ],
    synonyms: ['pompous', 'bombastic', 'high-flown'],
    origin: 'Latin grandis “grand” + loqui “to speak”.',
  },
  {
    word: 'sardonic',
    say: 'sar-DON-ik',
    pos: 'adjective',
    definition: 'Grimly mocking or cynical in a scornful way.',
    examples: [
      'She gave a sardonic smile at the empty apology.',
      'His sardonic wit spared no one at the table.',
    ],
    synonyms: ['mocking', 'cynical', 'sneering'],
    origin: 'Greek sardonios, associated with a bitter Sardinian plant said to cause grimacing.',
  },
  {
    word: 'ephemeron',
    say: 'ih-FEM-uh-ron',
    pos: 'noun',
    definition: 'Something that lasts only a day or a very short time.',
    examples: [
      'The mayfly is the classic ephemeron of the insect world.',
      'That trend was an ephemeron, forgotten within a week.',
    ],
    synonyms: ['transient', 'flash in the pan'],
    origin: 'Greek ephēmeron “lasting a day”.',
  },
  {
    word: 'inchoate',
    say: 'in-KOH-it',
    pos: 'adjective',
    definition: 'Just begun and so not fully formed or developed.',
    examples: [
      'She had only an inchoate idea of what to write.',
      'His inchoate plans slowly took definite shape.',
    ],
    synonyms: ['nascent', 'embryonic', 'unformed'],
    origin: 'Latin inchoare “to begin”.',
  },
  {
    word: 'perfunctory',
    say: 'per-FUNGK-tuh-ree',
    pos: 'adjective',
    definition: 'Done with minimum effort or care, as a routine duty.',
    examples: [
      'He gave the report a perfunctory glance and signed it.',
      'A perfunctory nod was the only greeting she offered.',
    ],
    synonyms: ['cursory', 'offhand', 'token'],
    origin: 'Latin perfunctorius “careless”, from perfungi “to get through”.',
  },
  {
    word: 'quotidian',
    say: 'kwoh-TID-ee-uhn',
    pos: 'adjective',
    definition: 'Ordinary and everyday; occurring daily.',
    examples: [
      'She found poetry in the most quotidian routines.',
      'The diary recorded the quotidian details of village life.',
    ],
    synonyms: ['everyday', 'mundane', 'commonplace'],
    origin: 'Latin quotidianus “daily”, from quotidie “every day”.',
  },
  {
    word: 'sempiternal',
    say: 'sem-pih-TUR-nuhl',
    pos: 'adjective',
    definition: 'Everlasting; enduring forever.',
    examples: [
      'The mountains felt sempiternal against the passing seasons.',
      'They spoke of a sempiternal bond that time could not break.',
    ],
    synonyms: ['eternal', 'everlasting', 'perpetual'],
    origin: 'Latin sempiternus, from semper “always” + aeternus “eternal”.',
  },
  {
    word: 'vituperative',
    say: 'vy-TOO-per-uh-tiv',
    pos: 'adjective',
    definition: 'Full of harsh, abusive criticism.',
    examples: [
      'The review was so vituperative it bordered on cruelty.',
      'He fired off a vituperative letter to the editor.',
    ],
    synonyms: ['abusive', 'scathing', 'vitriolic'],
    origin: 'Latin vituperare “to blame”.',
  },
  {
    word: 'apocryphal',
    say: 'uh-POK-rih-fuhl',
    pos: 'adjective',
    definition: 'Of doubtful authenticity, though widely circulated as true.',
    examples: [
      'The story of his last words is almost certainly apocryphal.',
      'That quote is apocryphal — he never actually said it.',
    ],
    synonyms: ['fictitious', 'spurious', 'unverified'],
    origin: 'Greek apokryphos “hidden”, from apokryptein “to hide away”.',
  },
  {
    word: 'truculent',
    say: 'TRUHK-yuh-luhnt',
    pos: 'adjective',
    definition: 'Eager or quick to argue or fight; aggressively defiant.',
    examples: [
      'He grew truculent whenever his methods were questioned.',
      'A truculent reply only deepened the quarrel.',
    ],
    synonyms: ['belligerent', 'combative', 'pugnacious'],
    origin: 'Latin truculentus “fierce”, from trux “savage”.',
  },
  {
    word: 'antediluvian',
    say: 'an-tih-dih-LOO-vee-uhn',
    pos: 'adjective',
    definition: 'Extremely old or old-fashioned; belonging to a time before the Biblical flood.',
    examples: [
      'His antediluvian phone still had a physical keypad.',
      'They laughed at the company’s antediluvian filing system.',
    ],
    synonyms: ['archaic', 'ancient', 'outmoded'],
    origin: 'Latin ante “before” + diluvium “flood”.',
  },
  {
    word: 'abstruse',
    say: 'ab-STROOS',
    pos: 'adjective',
    definition: 'Difficult to understand; obscure and deep.',
    examples: [
      'The lecture on abstruse tax law lost half the room.',
      'He delighted in abstruse puzzles no one else could solve.',
    ],
    synonyms: ['obscure', 'recondite', 'esoteric'],
    origin: 'Latin abstrusus “concealed”, from abstrudere “to hide away”.',
  },
  {
    word: 'munificent',
    say: 'myoo-NIF-ih-suhnt',
    pos: 'adjective',
    definition: 'Extremely generous, especially in giving.',
    examples: [
      'A munificent donor funded the entire library.',
      'They received a munificent gift they could never repay.',
    ],
    synonyms: ['bountiful', 'lavish', 'openhanded'],
    origin: 'Latin munificus “generous”, from munus “gift”.',
  },
  {
    word: 'obsequious',
    say: 'uhb-SEE-kwee-uhs',
    pos: 'adjective',
    definition: 'Excessively eager to please or obey; fawning.',
    examples: [
      'The obsequious waiter hovered over every table.',
      'His obsequious praise fooled no one.',
    ],
    synonyms: ['servile', 'fawning', 'sycophantic'],
    origin: 'Latin obsequiosus “compliant”, from obsequi “to comply”.',
  },
  {
    word: 'perfidious',
    say: 'per-FID-ee-uhs',
    pos: 'adjective',
    definition: 'Deceitful and untrustworthy; treacherous.',
    examples: [
      'A perfidious ally betrayed them at the worst moment.',
      'He was punished for his perfidious schemes.',
    ],
    synonyms: ['treacherous', 'disloyal', 'faithless'],
    origin: 'Latin perfidus “faithless”, from per- “through” + fides “faith”.',
  },
  {
    word: 'mendacious',
    say: 'men-DAY-shuhs',
    pos: 'adjective',
    definition: 'Not telling the truth; habitually lying.',
    examples: [
      'The mendacious witness contradicted himself twice.',
      'Her mendacious excuses eventually caught up with her.',
    ],
    synonyms: ['untruthful', 'dishonest', 'deceitful'],
    origin: 'Latin mendax “lying”.',
  },
  {
    word: 'loquacious',
    say: 'loh-KWAY-shuhs',
    pos: 'adjective',
    definition: 'Tending to talk a great deal; very talkative.',
    examples: [
      'The loquacious guide never paused for breath.',
      'A loquacious seatmate made the flight feel longer.',
    ],
    synonyms: ['garrulous', 'talkative', 'voluble'],
    origin: 'Latin loquax “talkative”, from loqui “to speak”.',
  },
  {
    word: 'taciturn',
    say: 'TAS-ih-turn',
    pos: 'adjective',
    definition: 'Saying very little; reserved in speech.',
    examples: [
      'The taciturn farmer answered only in nods.',
      'He grew taciturn whenever the subject came up.',
    ],
    synonyms: ['reticent', 'reserved', 'tight-lipped'],
    origin: 'Latin taciturnus “silent”, from tacere “to be silent”.',
  },
  {
    word: 'sagacious',
    say: 'suh-GAY-shuhs',
    pos: 'adjective',
    definition: 'Having keen judgment and practical wisdom.',
    examples: [
      'A sagacious investor sold before the crash.',
      'Her sagacious advice saved the company.',
    ],
    synonyms: ['wise', 'shrewd', 'astute'],
    origin: 'Latin sagax “of keen perception”.',
  },
  {
    word: 'fastidious',
    say: 'fa-STID-ee-uhs',
    pos: 'adjective',
    definition: 'Very attentive to detail and hard to please.',
    examples: [
      'He was fastidious about keeping his desk spotless.',
      'A fastidious editor caught every stray comma.',
    ],
    synonyms: ['meticulous', 'finicky', 'exacting'],
    origin: 'Latin fastidiosus “disdainful”, from fastidium “loathing”.',
  },
  {
    word: 'cantankerous',
    say: 'kan-TANG-ker-uhs',
    pos: 'adjective',
    definition: 'Bad-tempered, argumentative, and hard to deal with.',
    examples: [
      'The cantankerous old man shooed the children away.',
      'She grew cantankerous whenever she skipped lunch.',
    ],
    synonyms: ['irritable', 'crotchety', 'ornery'],
    origin: 'Perhaps from Middle English contakour “troublemaker”.',
  },
  {
    word: 'mercurial',
    say: 'mer-KYOOR-ee-uhl',
    pos: 'adjective',
    definition: 'Prone to sudden and unpredictable changes of mood.',
    examples: [
      'The director was brilliant but mercurial.',
      'His mercurial temper kept the whole office on edge.',
    ],
    synonyms: ['volatile', 'capricious', 'fickle'],
    origin: 'From Mercury, the swift, changeable Roman god.',
  },
  {
    word: 'capricious',
    say: 'kuh-PRISH-uhs',
    pos: 'adjective',
    definition: 'Given to sudden, unpredictable changes of behaviour.',
    examples: [
      'The capricious weather ruined their picnic plans.',
      'A capricious boss made every day a gamble.',
    ],
    synonyms: ['whimsical', 'fickle', 'erratic'],
    origin: 'Italian capriccio “sudden whim”.',
  },
  {
    word: 'ostentatious',
    say: 'os-ten-TAY-shuhs',
    pos: 'adjective',
    definition: 'Showy in a way meant to impress or attract attention.',
    examples: [
      'The ostentatious mansion dwarfed its neighbours.',
      'He wore an ostentatious watch to every meeting.',
    ],
    synonyms: ['showy', 'flashy', 'flamboyant'],
    origin: 'Latin ostentare “to display”.',
  },
  {
    word: 'surreptitious',
    say: 'sur-uhp-TISH-uhs',
    pos: 'adjective',
    definition: 'Done secretly to avoid being noticed.',
    examples: [
      'She stole a surreptitious glance at the answer sheet.',
      'They held surreptitious meetings after dark.',
    ],
    synonyms: ['furtive', 'clandestine', 'stealthy'],
    origin: 'Latin surrepticius “obtained secretly”, from surripere “to snatch”.',
  },
  {
    word: 'insidious',
    say: 'in-SID-ee-uhs',
    pos: 'adjective',
    definition: 'Gradually and secretly causing harm.',
    examples: [
      'The disease is insidious, with no early symptoms.',
      'An insidious rumour slowly poisoned their friendship.',
    ],
    synonyms: ['stealthy', 'treacherous', 'creeping'],
    origin: 'Latin insidiosus “cunning”, from insidiae “ambush”.',
  },
  {
    word: 'nefarious',
    say: 'nih-FAIR-ee-uhs',
    pos: 'adjective',
    definition: 'Wicked and criminal; extremely villainous.',
    examples: [
      'The spy uncovered a nefarious plot.',
      'Their nefarious dealings finally came to light.',
    ],
    synonyms: ['villainous', 'heinous', 'iniquitous'],
    origin: 'Latin nefarius “wicked”, from nefas “crime”.',
  },
  {
    word: 'iniquitous',
    say: 'ih-NIK-wih-tuhs',
    pos: 'adjective',
    definition: 'Grossly unfair or morally wrong.',
    examples: [
      'They fought against an iniquitous law.',
      'It was an iniquitous system that punished the poor.',
    ],
    synonyms: ['unjust', 'wicked', 'immoral'],
    origin: 'Latin iniquitas “injustice”, from in- “not” + aequus “equal”.',
  },
  {
    word: 'pernicious',
    say: 'per-NISH-uhs',
    pos: 'adjective',
    definition: 'Having a harmful effect, often in a subtle way.',
    examples: [
      'The pernicious habit crept up on him slowly.',
      'She warned of the pernicious influence of flattery.',
    ],
    synonyms: ['harmful', 'destructive', 'noxious'],
    origin: 'Latin perniciosus “destructive”, from pernicies “ruin”.',
  },
  {
    word: 'deleterious',
    say: 'del-ih-TEER-ee-uhs',
    pos: 'adjective',
    definition: 'Causing harm or damage.',
    examples: [
      'Too little sleep has deleterious effects on the mind.',
      'The chemical proved deleterious to the river’s fish.',
    ],
    synonyms: ['harmful', 'detrimental', 'injurious'],
    origin: 'Greek dēlētērios “noxious”, from dēleisthai “to harm”.',
  },
  {
    word: 'salubrious',
    say: 'suh-LOO-bree-uhs',
    pos: 'adjective',
    definition: 'Good for the health; pleasant and wholesome.',
    examples: [
      'They retired to the salubrious mountain air.',
      'The spa promised a salubrious change of pace.',
    ],
    synonyms: ['healthful', 'wholesome', 'invigorating'],
    origin: 'Latin salubris “healthful”, from salus “health”.',
  },
  {
    word: 'lachrymose',
    say: 'LAK-rih-mohs',
    pos: 'adjective',
    definition: 'Tearful or inclined to weep; mournful.',
    examples: [
      'The lachrymose farewell went on for an hour.',
      'She turned lachrymose at the sound of the old song.',
    ],
    synonyms: ['tearful', 'weepy', 'mournful'],
    origin: 'Latin lacrima “tear”.',
  },
  {
    word: 'maudlin',
    say: 'MAWD-lin',
    pos: 'adjective',
    definition: 'Sentimental in a weak, self-pitying way, often after drinking.',
    examples: [
      'He grew maudlin over old photographs.',
      'The film was maudlin and manipulative.',
    ],
    synonyms: ['mawkish', 'sentimental', 'weepy'],
    origin: 'From Mary Magdalene, often depicted weeping.',
  },
  {
    word: 'querulous',
    say: 'KWER-uh-luhs',
    pos: 'adjective',
    definition: 'Complaining in a peevish, whining way.',
    examples: [
      'A querulous voice rose from the back of the line.',
      'He became querulous whenever plans changed.',
    ],
    synonyms: ['peevish', 'petulant', 'whining'],
    origin: 'Latin querulus “complaining”, from queri “to complain”.',
  },
  {
    word: 'captious',
    say: 'KAP-shuhs',
    pos: 'adjective',
    definition: 'Overly eager to find fault or raise petty objections.',
    examples: [
      'A captious critic nitpicked every line.',
      'His captious remarks drained the room’s energy.',
    ],
    synonyms: ['carping', 'faultfinding', 'hypercritical'],
    origin: 'Latin captiosus “fallacious”, from capere “to seize”.',
  },
  {
    word: 'contumacious',
    say: 'kon-too-MAY-shuhs',
    pos: 'adjective',
    definition: 'Stubbornly disobedient to authority.',
    examples: [
      'The contumacious defendant defied the judge.',
      'A contumacious student refused every instruction.',
    ],
    synonyms: ['defiant', 'insubordinate', 'rebellious'],
    origin: 'Latin contumacia “stubbornness”.',
  },
  {
    word: 'pertinacious',
    say: 'pur-tih-NAY-shuhs',
    pos: 'adjective',
    definition: 'Holding firmly to an opinion or course of action; stubbornly persistent.',
    examples: [
      'Her pertinacious pursuit of the truth paid off.',
      'A pertinacious salesman would not take no for an answer.',
    ],
    synonyms: ['tenacious', 'dogged', 'unyielding'],
    origin: 'Latin pertinax “holding fast”, from per- “very” + tenax “tenacious”.',
  },
  {
    word: 'mendicant',
    say: 'MEN-dih-kuhnt',
    pos: 'noun',
    definition: 'A beggar, or a member of a religious order living on alms.',
    examples: [
      'A mendicant sat by the temple gate.',
      'The monk lived as a mendicant, owning nothing.',
    ],
    synonyms: ['beggar', 'almsman', 'pauper'],
    origin: 'Latin mendicare “to beg”.',
  },
  {
    word: 'peripatetic',
    say: 'per-ih-puh-TET-ik',
    pos: 'adjective',
    definition: 'Travelling from place to place; itinerant.',
    examples: [
      'Her peripatetic childhood spanned five countries.',
      'He led a peripatetic life as a touring musician.',
    ],
    synonyms: ['itinerant', 'roving', 'nomadic'],
    origin: 'Greek peripatētikos “walking about”, from Aristotle’s pacing lectures.',
  },
  {
    word: 'itinerant',
    say: 'eye-TIN-er-uhnt',
    pos: 'adjective',
    definition: 'Travelling from place to place, especially for work.',
    examples: [
      'Itinerant workers followed the harvest north.',
      'He spent years as an itinerant preacher.',
    ],
    synonyms: ['wandering', 'roaming', 'migratory'],
    origin: 'Latin itinerari “to travel”, from iter “journey”.',
  },
  {
    word: 'sedulous',
    say: 'SEJ-uh-luhs',
    pos: 'adjective',
    definition: 'Showing dedication and careful, steady effort.',
    examples: [
      'Her sedulous note-taking filled a dozen notebooks.',
      'Sedulous practice slowly perfected his craft.',
    ],
    synonyms: ['diligent', 'assiduous', 'painstaking'],
    origin: 'Latin sedulus “diligent”.',
  },
  {
    word: 'assiduous',
    say: 'uh-SIJ-oo-uhs',
    pos: 'adjective',
    definition: 'Showing great care, attention, and persistent effort.',
    examples: [
      'An assiduous researcher, she checked every source twice.',
      'His assiduous training earned him a place on the team.',
    ],
    synonyms: ['diligent', 'industrious', 'meticulous'],
    origin: 'Latin assiduus “constant”, from assidere “to sit beside”.',
  },
  {
    word: 'indefatigable',
    say: 'in-dih-FAT-ih-guh-buhl',
    pos: 'adjective',
    definition: 'Never tiring; persisting tirelessly.',
    examples: [
      'The indefatigable volunteer worked through the night.',
      'She was indefatigable in her search for the truth.',
    ],
    synonyms: ['tireless', 'unflagging', 'untiring'],
    origin: 'Latin indefatigabilis, from in- “not” + defatigare “to tire out”.',
  },
  {
    word: 'intransigent',
    say: 'in-TRAN-sih-juhnt',
    pos: 'adjective',
    definition: 'Refusing to change one’s views or compromise.',
    examples: [
      'Both sides remained intransigent, and talks collapsed.',
      'His intransigent stance cost him allies.',
    ],
    synonyms: ['uncompromising', 'inflexible', 'obstinate'],
    origin: 'Spanish intransigente “not compromising”.',
  },
  {
    word: 'obdurate',
    say: 'OB-dur-it',
    pos: 'adjective',
    definition: 'Stubbornly refusing to change one’s mind.',
    examples: [
      'He remained obdurate despite every plea.',
      'The board was obdurate about the budget cuts.',
    ],
    synonyms: ['unyielding', 'inflexible', 'adamant'],
    origin: 'Latin obduratus “hardened”, from durus “hard”.',
  },
  {
    word: 'impecunious',
    say: 'im-pih-KYOO-nee-uhs',
    pos: 'adjective',
    definition: 'Having little or no money.',
    examples: [
      'The impecunious student lived on rice and hope.',
      'An impecunious artist, he traded paintings for meals.',
    ],
    synonyms: ['penniless', 'destitute', 'penurious'],
    origin: 'Latin in- “not” + pecunia “money”.',
  },
  {
    word: 'penurious',
    say: 'puh-NOOR-ee-uhs',
    pos: 'adjective',
    definition: 'Extremely poor, or unwilling to spend money; stingy.',
    examples: [
      'They scraped by in penurious circumstances.',
      'His penurious habits shocked his wealthy friends.',
    ],
    synonyms: ['impoverished', 'miserly', 'niggardly'],
    origin: 'Latin penuria “want, scarcity”.',
  },
  {
    word: 'parsimonious',
    say: 'par-sih-MOH-nee-uhs',
    pos: 'adjective',
    definition: 'Extremely unwilling to spend money or use resources.',
    examples: [
      'The parsimonious landlord refused every repair.',
      'She was parsimonious with praise but generous with blame.',
    ],
    synonyms: ['stingy', 'miserly', 'tightfisted'],
    origin: 'Latin parsimonia “thrift”, from parcere “to spare”.',
  },
  {
    word: 'prodigal',
    say: 'PROD-ih-guhl',
    pos: 'adjective',
    definition: 'Spending money or resources recklessly and wastefully.',
    examples: [
      'His prodigal spending emptied the inheritance.',
      'They were prodigal with praise on opening night.',
    ],
    synonyms: ['wasteful', 'extravagant', 'lavish'],
    origin: 'Latin prodigus “wasteful”, from prodigere “to squander”.',
  },
  {
    word: 'profligate',
    say: 'PROF-lih-git',
    pos: 'adjective',
    definition: 'Recklessly wasteful or shamelessly immoral.',
    examples: [
      'The regime was notorious for profligate spending.',
      'He abandoned his profligate ways and settled down.',
    ],
    synonyms: ['wasteful', 'dissolute', 'extravagant'],
    origin: 'Latin profligatus “ruined”, from profligare “to overthrow”.',
  },
  {
    word: 'rapacious',
    say: 'ruh-PAY-shuhs',
    pos: 'adjective',
    definition: 'Aggressively greedy or grasping.',
    examples: [
      'Rapacious lenders preyed on desperate families.',
      'The company had a rapacious appetite for land.',
    ],
    synonyms: ['greedy', 'grasping', 'voracious'],
    origin: 'Latin rapax “grasping”, from rapere “to seize”.',
  },
  {
    word: 'avaricious',
    say: 'av-uh-RISH-uhs',
    pos: 'adjective',
    definition: 'Having an extreme greed for wealth.',
    examples: [
      'The avaricious merchant hoarded every coin.',
      'Avaricious executives bled the company dry.',
    ],
    synonyms: ['greedy', 'covetous', 'grasping'],
    origin: 'Latin avarus “greedy”.',
  },
  {
    word: 'voracious',
    say: 'vaw-RAY-shuhs',
    pos: 'adjective',
    definition: 'Wanting or devouring great amounts, as of food or knowledge.',
    examples: [
      'A voracious reader, she finished a book a day.',
      'The travellers arrived with voracious appetites.',
    ],
    synonyms: ['insatiable', 'ravenous', 'greedy'],
    origin: 'Latin vorax “devouring”, from vorare “to swallow”.',
  },
  {
    word: 'insatiable',
    say: 'in-SAY-shuh-buhl',
    pos: 'adjective',
    definition: 'Impossible to satisfy.',
    examples: [
      'He had an insatiable curiosity about everything.',
      'The market’s insatiable demand kept prices high.',
    ],
    synonyms: ['unquenchable', 'voracious', 'unappeasable'],
    origin: 'Latin insatiabilis, from in- “not” + satiare “to satisfy”.',
  },
  {
    word: 'sybaritic',
    say: 'sib-uh-RIT-ik',
    pos: 'adjective',
    definition: 'Fond of luxury and sensual pleasure.',
    examples: [
      'They spent a sybaritic weekend at the seaside resort.',
      'His sybaritic tastes ran to silk sheets and fine wine.',
    ],
    synonyms: ['luxurious', 'hedonistic', 'self-indulgent'],
    origin: 'From Sybaris, an ancient Greek city famed for its luxury.',
  },
  {
    word: 'epicurean',
    say: 'ep-ih-kyoo-REE-uhn',
    pos: 'adjective',
    definition: 'Devoted to refined sensual enjoyment, especially of food and drink.',
    examples: [
      'The dinner was an epicurean feast of rare dishes.',
      'He brought an epicurean eye to every menu.',
    ],
    synonyms: ['gourmet', 'hedonistic', 'sensual'],
    origin: 'From Epicurus, the Greek philosopher of pleasure.',
  },
  {
    word: 'ascetic',
    say: 'uh-SET-ik',
    pos: 'adjective',
    definition: 'Practising severe self-discipline and abstaining from pleasure.',
    examples: [
      'The monk led an ascetic life of prayer and fasting.',
      'His ascetic room held only a cot and a candle.',
    ],
    synonyms: ['austere', 'self-denying', 'abstinent'],
    origin: 'Greek askētēs “monk, hermit”, from askein “to exercise”.',
  },
  {
    word: 'abstemious',
    say: 'ab-STEE-mee-uhs',
    pos: 'adjective',
    definition: 'Sparing or moderate, especially in eating and drinking.',
    examples: [
      'An abstemious eater, he never took a second helping.',
      'She stayed abstemious even at the lavish banquet.',
    ],
    synonyms: ['temperate', 'moderate', 'self-restrained'],
    origin: 'Latin abstemius, from abs- “from” + temetum “strong drink”.',
  },
  {
    word: 'abnegation',
    say: 'ab-nih-GAY-shuhn',
    pos: 'noun',
    definition: 'The act of renouncing or denying oneself something.',
    examples: [
      'Their vows demanded complete abnegation of wealth.',
      'His self-abnegation bordered on the extreme.',
    ],
    synonyms: ['renunciation', 'self-denial', 'sacrifice'],
    origin: 'Latin abnegare “to refuse”.',
  },
  {
    word: 'propitiate',
    say: 'proh-PISH-ee-ayt',
    pos: 'verb',
    definition: 'To win or regain the favour of someone by doing something pleasing.',
    examples: [
      'They offered gifts to propitiate the angry chief.',
      'He tried to propitiate his critics with an apology.',
    ],
    synonyms: ['appease', 'placate', 'mollify'],
    origin: 'Latin propitiare “to make favourable”.',
  },
  {
    word: 'mollify',
    say: 'MOL-ih-fy',
    pos: 'verb',
    definition: 'To soothe the anger or anxiety of someone.',
    examples: [
      'A quick apology mollified the furious customer.',
      'Nothing could mollify her wounded pride.',
    ],
    synonyms: ['pacify', 'appease', 'placate'],
    origin: 'Latin mollificare “to soften”, from mollis “soft”.',
  },
  {
    word: 'assuage',
    say: 'uh-SWAYJ',
    pos: 'verb',
    definition: 'To make an unpleasant feeling less intense.',
    examples: [
      'A warm meal assuaged their hunger and their fear.',
      'Nothing he said could assuage her guilt.',
    ],
    synonyms: ['ease', 'relieve', 'soothe'],
    origin: 'Latin assuaviare “to sweeten”, via Old French assouagier.',
  },
  {
    word: 'ameliorate',
    say: 'uh-MEEL-yuh-rayt',
    pos: 'verb',
    definition: 'To make a bad or unsatisfactory situation better.',
    examples: [
      'The new policy did little to ameliorate poverty.',
      'Shade trees ameliorate the summer heat.',
    ],
    synonyms: ['improve', 'better', 'alleviate'],
    origin: 'Latin melior “better”, via French améliorer.',
  },
  {
    word: 'exacerbate',
    say: 'ig-ZAS-er-bayt',
    pos: 'verb',
    definition: 'To make a problem or bad situation worse.',
    examples: [
      'Shouting only exacerbated the tension.',
      'The drought exacerbated the food shortage.',
    ],
    synonyms: ['aggravate', 'worsen', 'inflame'],
    origin: 'Latin exacerbare “to irritate”, from acerbus “harsh”.',
  },
  {
    word: 'attenuate',
    say: 'uh-TEN-yoo-ayt',
    pos: 'verb',
    definition: 'To reduce the force, effect, or value of something.',
    examples: [
      'Distance attenuates the signal’s strength.',
      'Time gradually attenuated his anger.',
    ],
    synonyms: ['weaken', 'diminish', 'lessen'],
    origin: 'Latin attenuare “to make thin”, from tenuis “thin”.',
  },
  {
    word: 'vitiate',
    say: 'VISH-ee-ayt',
    pos: 'verb',
    definition: 'To spoil or reduce the quality or effectiveness of something.',
    examples: [
      'One error can vitiate the whole experiment.',
      'Fraud vitiates the entire contract.',
    ],
    synonyms: ['impair', 'undermine', 'corrupt'],
    origin: 'Latin vitiare “to spoil”, from vitium “fault”.',
  },
  {
    word: 'adulterate',
    say: 'uh-DUHL-ter-ayt',
    pos: 'verb',
    definition: 'To make something poorer in quality by adding an inferior substance.',
    examples: [
      'Dishonest sellers adulterated the honey with syrup.',
      'The wine had been adulterated with water.',
    ],
    synonyms: ['dilute', 'debase', 'contaminate'],
    origin: 'Latin adulterare “to corrupt”.',
  },
  {
    word: 'calumny',
    say: 'KAL-uhm-nee',
    pos: 'noun',
    definition: 'A false statement made to damage someone’s reputation.',
    examples: [
      'He sued the paper for calumny.',
      'Her rivals spread calumny to discredit her.',
    ],
    synonyms: ['slander', 'defamation', 'libel'],
    origin: 'Latin calumnia “false accusation”.',
  },
  {
    word: 'obloquy',
    say: 'OB-luh-kwee',
    pos: 'noun',
    definition: 'Strong public condemnation, or the disgrace it brings.',
    examples: [
      'The scandal brought years of obloquy.',
      'He endured obloquy for his unpopular stance.',
    ],
    synonyms: ['censure', 'vilification', 'disgrace'],
    origin: 'Latin obloqui “to speak against”.',
  },
  {
    word: 'opprobrium',
    say: 'uh-PROH-bree-uhm',
    pos: 'noun',
    definition: 'Harsh criticism and public disgrace resulting from bad conduct.',
    examples: [
      'The verdict heaped opprobrium on the company.',
      'He faced the opprobrium of his entire profession.',
    ],
    synonyms: ['disgrace', 'scorn', 'infamy'],
    origin: 'Latin opprobrium “reproach”, from probrum “shameful act”.',
  },
  {
    word: 'approbation',
    say: 'ap-ruh-BAY-shuhn',
    pos: 'noun',
    definition: 'Approval or praise.',
    examples: [
      'The plan met with the committee’s approbation.',
      'She glowed under her mentor’s approbation.',
    ],
    synonyms: ['approval', 'commendation', 'praise'],
    origin: 'Latin approbare “to approve”.',
  },
  {
    word: 'adulation',
    say: 'aj-uh-LAY-shuhn',
    pos: 'noun',
    definition: 'Excessive admiration or flattery.',
    examples: [
      'The young star basked in the crowd’s adulation.',
      'He mistook their adulation for genuine respect.',
    ],
    synonyms: ['flattery', 'worship', 'fawning'],
    origin: 'Latin adulari “to flatter”.',
  },
  {
    word: 'obeisance',
    say: 'oh-BAY-suhns',
    pos: 'noun',
    definition: 'A gesture or attitude of deep respect or submission.',
    examples: [
      'The courtiers made obeisance to the queen.',
      'He refused to pay obeisance to the new regime.',
    ],
    synonyms: ['homage', 'deference', 'reverence'],
    origin: 'Old French obeissance “obedience”.',
  },
  {
    word: 'fealty',
    say: 'FEE-uhl-tee',
    pos: 'noun',
    definition: 'A solemn duty of loyalty, especially to a lord or cause.',
    examples: [
      'The knights swore fealty to the king.',
      'She kept her fealty to the old ideals.',
    ],
    synonyms: ['allegiance', 'loyalty', 'fidelity'],
    origin: 'Old French feaulte, from Latin fidelitas “faithfulness”.',
  },
  {
    word: 'probity',
    say: 'PROH-bih-tee',
    pos: 'noun',
    definition: 'Complete honesty and moral integrity.',
    examples: [
      'The judge was known for her unshakeable probity.',
      'His financial probity was beyond question.',
    ],
    synonyms: ['integrity', 'rectitude', 'honesty'],
    origin: 'Latin probitas “uprightness”, from probus “good”.',
  },
  {
    word: 'rectitude',
    say: 'REK-tih-tood',
    pos: 'noun',
    definition: 'Morally correct behaviour or thinking.',
    examples: [
      'He was admired for his rectitude in office.',
      'Their moral rectitude allowed no shortcuts.',
    ],
    synonyms: ['righteousness', 'integrity', 'virtue'],
    origin: 'Latin rectitudo “straightness”, from rectus “right”.',
  },
  {
    word: 'turpitude',
    say: 'TUR-pih-tood',
    pos: 'noun',
    definition: 'Depravity; wicked or corrupt behaviour.',
    examples: [
      'He was dismissed for moral turpitude.',
      'The novel exposed the turpitude of the court.',
    ],
    synonyms: ['depravity', 'corruption', 'wickedness'],
    origin: 'Latin turpitudo “baseness”, from turpis “shameful”.',
  },
  {
    word: 'perfidy',
    say: 'PUR-fih-dee',
    pos: 'noun',
    definition: 'Deceit and betrayal of trust.',
    examples: [
      'The general’s perfidy doomed the campaign.',
      'She never forgave his perfidy.',
    ],
    synonyms: ['treachery', 'betrayal', 'disloyalty'],
    origin: 'Latin perfidia “faithlessness”, from perfidus “treacherous”.',
  },
  {
    word: 'mendacity',
    say: 'men-DAS-ih-tee',
    pos: 'noun',
    definition: 'The tendency to lie; untruthfulness.',
    examples: [
      'The play is a study of family mendacity.',
      'His mendacity finally destroyed his credibility.',
    ],
    synonyms: ['dishonesty', 'deceit', 'untruthfulness'],
    origin: 'Latin mendacitas, from mendax “lying”.',
  },
  {
    word: 'veracity',
    say: 'vuh-RAS-ih-tee',
    pos: 'noun',
    definition: 'Conformity to truth; habitual truthfulness.',
    examples: [
      'No one doubted the veracity of her account.',
      'The lawyer questioned the witness’s veracity.',
    ],
    synonyms: ['truthfulness', 'accuracy', 'honesty'],
    origin: 'Latin verax “truthful”, from verus “true”.',
  },
  {
    word: 'duplicity',
    say: 'doo-PLIS-ih-tee',
    pos: 'noun',
    definition: 'Deceitfulness in speech or conduct; double-dealing.',
    examples: [
      'His duplicity cost him every friendship.',
      'The deal collapsed once her duplicity was exposed.',
    ],
    synonyms: ['deceit', 'double-dealing', 'treachery'],
    origin: 'Latin duplicitas “doubleness”, from duplex “twofold”.',
  },
  {
    word: 'chicanery',
    say: 'shih-KAY-nuh-ree',
    pos: 'noun',
    definition: 'The use of clever but deceptive tricks to achieve a goal.',
    examples: [
      'Legal chicanery kept the case tied up for years.',
      'They won through outright chicanery.',
    ],
    synonyms: ['trickery', 'deception', 'skulduggery'],
    origin: 'French chicanerie “quibbling”.',
  },
  {
    word: 'subterfuge',
    say: 'SUHB-ter-fyooj',
    pos: 'noun',
    definition: 'A deceptive trick used to achieve or avoid something.',
    examples: [
      'They entered by subterfuge, posing as inspectors.',
      'No subterfuge could hide the missing funds.',
    ],
    synonyms: ['deception', 'ruse', 'trickery'],
    origin: 'Latin subterfugere “to escape secretly”.',
  },
  {
    word: 'artifice',
    say: 'AR-tih-fis',
    pos: 'noun',
    definition: 'Clever or cunning trickery, or a device used to deceive.',
    examples: [
      'The magician’s art is built on pure artifice.',
      'Her charm was genuine, without a trace of artifice.',
    ],
    synonyms: ['trickery', 'cunning', 'stratagem'],
    origin: 'Latin artificium “craftsmanship”, from ars “art” + facere “to make”.',
  },
  {
    word: 'legerdemain',
    say: 'lej-er-duh-MAYN',
    pos: 'noun',
    definition: 'Skilful sleight of hand; cunning deception.',
    examples: [
      'The card trick was a marvel of legerdemain.',
      'Their accounting relied on financial legerdemain.',
    ],
    synonyms: ['sleight of hand', 'trickery', 'conjuring'],
    origin: 'Old French leger de main “light of hand”.',
  },
  {
    word: 'prestidigitation',
    say: 'pres-tih-dij-ih-TAY-shuhn',
    pos: 'noun',
    definition: 'Skilful conjuring or sleight of hand for entertainment.',
    examples: [
      'The show closed with dazzling prestidigitation.',
      'His prestidigitation left the audience gasping.',
    ],
    synonyms: ['sleight of hand', 'conjuring', 'magic'],
    origin: 'French prestidigitateur, from preste “nimble” + Latin digitus “finger”.',
  },
  {
    word: 'machination',
    say: 'mak-ih-NAY-shuhn',
    pos: 'noun',
    definition: 'A crafty scheme or plot intended to do harm.',
    examples: [
      'The novel is full of courtly machinations.',
      'Their machinations to seize control finally failed.',
    ],
    synonyms: ['scheme', 'intrigue', 'plot'],
    origin: 'Latin machinari “to contrive”, from machina “device”.',
  },
  {
    word: 'cabal',
    say: 'kuh-BAL',
    pos: 'noun',
    definition: 'A small group secretly plotting to gain power or influence.',
    examples: [
      'A cabal of ministers plotted the coup.',
      'Rumours spread of a cabal running the company.',
    ],
    synonyms: ['clique', 'faction', 'conspiracy'],
    origin: 'French cabale, from Hebrew qabbālāh “received tradition”.',
  },
  {
    word: 'coterie',
    say: 'KOH-tuh-ree',
    pos: 'noun',
    definition: 'A small, exclusive group of people with shared interests.',
    examples: [
      'A coterie of artists gathered at the café each night.',
      'She belonged to a coterie of young reformers.',
    ],
    synonyms: ['clique', 'circle', 'set'],
    origin: 'French coterie “an association of tenants”.',
  },
  {
    word: 'conclave',
    say: 'KON-klayv',
    pos: 'noun',
    definition: 'A private or secret meeting, especially of a select group.',
    examples: [
      'The leaders met in conclave to choose a successor.',
      'Reporters waited outside the closed conclave.',
    ],
    synonyms: ['assembly', 'council', 'gathering'],
    origin: 'Latin conclave “a lockable room”, from clavis “key”.',
  },
  {
    word: 'cornucopia',
    say: 'kor-nuh-KOH-pee-uh',
    pos: 'noun',
    definition: 'An abundant, overflowing supply of good things.',
    examples: [
      'The market was a cornucopia of autumn produce.',
      'The archive is a cornucopia for historians.',
    ],
    synonyms: ['abundance', 'wealth', 'bounty'],
    origin: 'Latin cornu copiae “horn of plenty”.',
  },
  {
    word: 'plethora',
    say: 'PLETH-uh-ruh',
    pos: 'noun',
    definition: 'An amount that is more than enough; an excess.',
    examples: [
      'The menu offered a plethora of choices.',
      'A plethora of forms buried the simple request.',
    ],
    synonyms: ['excess', 'surplus', 'abundance'],
    origin: 'Greek plēthōra “fullness”, from plēthein “to be full”.',
  },
  {
    word: 'surfeit',
    say: 'SUR-fit',
    pos: 'noun',
    definition: 'An excessive amount of something.',
    examples: [
      'A surfeit of rich food left them queasy.',
      'There was a surfeit of talent and a shortage of jobs.',
    ],
    synonyms: ['excess', 'glut', 'overabundance'],
    origin: 'Old French surfait “overdone”, from Latin superfacere.',
  },
  {
    word: 'superfluity',
    say: 'soo-per-FLOO-ih-tee',
    pos: 'noun',
    definition: 'An unnecessarily large amount of something.',
    examples: [
      'The essay drowned in a superfluity of adjectives.',
      'They lived amid a superfluity of gadgets.',
    ],
    synonyms: ['excess', 'surplus', 'glut'],
    origin: 'Latin superfluus “overflowing”, from super- “over” + fluere “to flow”.',
  },
  {
    word: 'pleonasm',
    say: 'PLEE-uh-naz-uhm',
    pos: 'noun',
    definition: 'The use of more words than needed to express a meaning.',
    examples: [
      '“Free gift” is a common pleonasm.',
      'The editor trimmed every pleonasm from the draft.',
    ],
    synonyms: ['redundancy', 'tautology', 'verbosity'],
    origin: 'Greek pleonasmos “excess”, from pleonazein “to be superfluous”.',
  },
  {
    word: 'tautology',
    say: 'taw-TOL-uh-jee',
    pos: 'noun',
    definition: 'Saying the same thing twice in different words, needlessly.',
    examples: [
      '“A brief summary” verges on tautology.',
      'The proof was dismissed as an empty tautology.',
    ],
    synonyms: ['redundancy', 'repetition', 'pleonasm'],
    origin: 'Greek tautologos “repeating what has been said”.',
  },
  {
    word: 'circumlocution',
    say: 'sur-kuhm-loh-KYOO-shuhn',
    pos: 'noun',
    definition: 'The use of many words where fewer would do; talking in a roundabout way.',
    examples: [
      'Cut the circumlocution and give me the answer.',
      'His circumlocution hid a very simple point.',
    ],
    synonyms: ['verbosity', 'wordiness', 'evasion'],
    origin: 'Latin circum “around” + locutio “speaking”.',
  },
  {
    word: 'periphrasis',
    say: 'puh-RIF-ruh-sis',
    pos: 'noun',
    definition: 'The use of indirect and wordy language instead of a plain term.',
    examples: [
      'By periphrasis he called death “the great leveller”.',
      'The report’s periphrasis obscured its message.',
    ],
    synonyms: ['circumlocution', 'roundaboutness', 'wordiness'],
    origin: 'Greek periphrasis “roundabout speech”.',
  },
  {
    word: 'verbiage',
    say: 'VUR-bee-ij',
    pos: 'noun',
    definition: 'Excessive or meaningless use of words.',
    examples: [
      'The contract was buried in legal verbiage.',
      'Strip away the verbiage and the idea is thin.',
    ],
    synonyms: ['wordiness', 'padding', 'waffle'],
    origin: 'French verbiage, from verbe “word”.',
  },
  {
    word: 'bombast',
    say: 'BOM-bast',
    pos: 'noun',
    definition: 'High-sounding language with little real meaning.',
    examples: [
      'The speech was pure bombast, all noise and no plan.',
      'Critics mocked the film’s patriotic bombast.',
    ],
    synonyms: ['pomposity', 'grandiloquence', 'rhetoric'],
    origin: 'From bombast “cotton padding”, later “inflated speech”.',
  },
  {
    word: 'rodomontade',
    say: 'rod-uh-mon-TAYD',
    pos: 'noun',
    definition: 'Boastful or inflated talk; bragging.',
    examples: [
      'His rodomontade about past triumphs bored everyone.',
      'The manifesto was mostly rodomontade.',
    ],
    synonyms: ['bragging', 'bluster', 'boasting'],
    origin: 'From Rodomonte, a boastful king in Italian epic poetry.',
  },
  {
    word: 'braggadocio',
    say: 'brag-uh-DOH-shee-oh',
    pos: 'noun',
    definition: 'Boastful or arrogant behaviour and talk.',
    examples: [
      'Beneath the braggadocio was a nervous rookie.',
      'His pre-match braggadocio did not survive the first round.',
    ],
    synonyms: ['bravado', 'swagger', 'boastfulness'],
    origin: 'From Braggadocchio, a boastful character in Spenser’s poetry.',
  },
  {
    word: 'hubris',
    say: 'HYOO-bris',
    pos: 'noun',
    definition: 'Excessive pride or self-confidence that leads to downfall.',
    examples: [
      'His hubris blinded him to the coming collapse.',
      'The tragedy turns on the hero’s hubris.',
    ],
    synonyms: ['arrogance', 'conceit', 'overconfidence'],
    origin: 'Greek hybris “insolence, outrage”.',
  },
  {
    word: 'hauteur',
    say: 'hoh-TUR',
    pos: 'noun',
    definition: 'Haughty, arrogant manner; disdainful pride.',
    examples: [
      'She swept past with icy hauteur.',
      'His hauteur alienated even his allies.',
    ],
    synonyms: ['haughtiness', 'arrogance', 'disdain'],
    origin: 'French hauteur “height, loftiness”, from haut “high”.',
  },
  {
    word: 'supercilious',
    say: 'soo-per-SIL-ee-uhs',
    pos: 'adjective',
    definition: 'Behaving as though superior to others; haughtily disdainful.',
    examples: [
      'The clerk gave a supercilious little sneer.',
      'His supercilious tone irritated the whole class.',
    ],
    synonyms: ['haughty', 'disdainful', 'condescending'],
    origin: 'Latin supercilium “eyebrow, haughtiness”.',
  },
  {
    word: 'contumely',
    say: 'KON-too-muh-lee',
    pos: 'noun',
    definition: 'Insolent or insulting treatment; contemptuous rudeness.',
    examples: [
      'He bore the contumely of the crowd in silence.',
      'Years of contumely had hardened her.',
    ],
    synonyms: ['insolence', 'scorn', 'abuse'],
    origin: 'Latin contumelia “insult, reproach”.',
  },
  {
    word: 'effrontery',
    say: 'ih-FRUHN-tuh-ree',
    pos: 'noun',
    definition: 'Shameless boldness; insolent audacity.',
    examples: [
      'He had the effrontery to ask for a raise after failing.',
      'Their effrontery in denying it astonished everyone.',
    ],
    synonyms: ['audacity', 'impudence', 'nerve'],
    origin: 'French effronterie, from Latin effrons “shameless”.',
  },
  {
    word: 'temerity',
    say: 'tuh-MER-ih-tee',
    pos: 'noun',
    definition: 'Excessive boldness or rashness; reckless nerve.',
    examples: [
      'She had the temerity to challenge the champion.',
      'No one else had the temerity to speak up.',
    ],
    synonyms: ['audacity', 'recklessness', 'nerve'],
    origin: 'Latin temeritas “rashness”, from temere “rashly”.',
  },
  {
    word: 'impudence',
    say: 'IM-pyoo-duhns',
    pos: 'noun',
    definition: 'Bold disrespect or rudeness; cheek.',
    examples: [
      'The child’s impudence stunned the teacher.',
      'He answered back with astonishing impudence.',
    ],
    synonyms: ['insolence', 'cheek', 'audacity'],
    origin: 'Latin impudens “shameless”, from in- “not” + pudere “to feel shame”.',
  },
  {
    word: 'impertinence',
    say: 'im-PUR-tih-nuhns',
    pos: 'noun',
    definition: 'Rude, disrespectful behaviour, especially toward a superior.',
    examples: [
      'She was scolded for her impertinence.',
      'His impertinence to the judge nearly earned a fine.',
    ],
    synonyms: ['insolence', 'rudeness', 'cheek'],
    origin: 'Latin impertinens “not belonging”, later “presumptuous”.',
  },
  {
    word: 'insouciance',
    say: 'in-SOO-see-uhns',
    pos: 'noun',
    definition: 'A casual lack of concern; carefree indifference.',
    examples: [
      'She shrugged off the danger with cheerful insouciance.',
      'His insouciance in a crisis was almost enviable.',
    ],
    synonyms: ['nonchalance', 'indifference', 'unconcern'],
    origin: 'French insouciance, from in- “not” + soucier “to worry”.',
  },
];
