// Word data for Wordle. Two lists:
//  - ANSWERS: common, fair five-letter words used as hidden solutions.
//  - EXTRA_ALLOWED: additional valid five-letter words accepted as guesses
//    but never chosen as answers (so solutions stay guessable).
// VALID_GUESSES is the union — a guess must be in it to be submitted.

export const ANSWERS: readonly string[] = [
  'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult', 'after', 'again',
  'agent', 'agree', 'ahead', 'alarm', 'album', 'alert', 'alike', 'alive', 'allow', 'alone',
  'along', 'alter', 'among', 'anger', 'angle', 'angry', 'apart', 'apple', 'apply', 'arena',
  'argue', 'arise', 'array', 'aside', 'asset', 'audio', 'audit', 'avoid', 'award', 'aware',
  'badly', 'baker', 'basic', 'basis', 'beach', 'began', 'begin', 'begun', 'being', 'below',
  'bench', 'billy', 'birth', 'black', 'blame', 'blank', 'blast', 'blend', 'bless', 'blind',
  'block', 'blood', 'bloom', 'board', 'boast', 'bonus', 'boost', 'booth', 'bound', 'brain',
  'brand', 'brave', 'bread', 'break', 'breed', 'brick', 'bride', 'brief', 'bring', 'broad',
  'broke', 'brown', 'brush', 'build', 'built', 'bunch', 'burst', 'buyer', 'cabin', 'cable',
  'candy', 'cargo', 'carry', 'catch', 'cause', 'chain', 'chair', 'chalk', 'chaos', 'charm',
  'chart', 'chase', 'cheap', 'check', 'chess', 'chest', 'chief', 'child', 'chill', 'china',
  'chose', 'civic', 'civil', 'claim', 'class', 'clean', 'clear', 'clerk', 'click', 'cliff',
  'climb', 'cling', 'clock', 'close', 'cloth', 'cloud', 'clown', 'coach', 'coast', 'could',
  'count', 'court', 'cover', 'crack', 'craft', 'crash', 'crazy', 'cream', 'crime', 'crisp',
  'cross', 'crowd', 'crown', 'crude', 'cruel', 'crush', 'curve', 'cycle', 'daily', 'dairy',
  'dance', 'dated', 'dealt', 'death', 'debut', 'delay', 'dense', 'depth', 'devil', 'diary',
  'digit', 'dirty', 'ditch', 'dodge', 'doing', 'donor', 'doubt', 'dozen', 'draft', 'drain',
  'drama', 'drank', 'dream', 'dress', 'dried', 'drift', 'drill', 'drink', 'drive', 'drove',
  'drown', 'eager', 'eagle', 'early', 'earth', 'eight', 'elbow', 'elder', 'elect', 'elite',
  'empty', 'enemy', 'enjoy', 'enter', 'entry', 'equal', 'error', 'essay', 'event', 'every',
  'exact', 'exams', 'exist', 'extra', 'faith', 'false', 'fancy', 'fatal', 'fault', 'favor',
  'fence', 'ferry', 'fever', 'field', 'fifth', 'fifty', 'fight', 'final', 'first', 'fixed',
  'flame', 'flash', 'fleet', 'flesh', 'float', 'flock', 'flood', 'floor', 'flour', 'fluid',
  'flush', 'focal', 'focus', 'force', 'forge', 'forth', 'forty', 'forum', 'found', 'frame',
  'frank', 'fraud', 'fresh', 'front', 'frost', 'fruit', 'fully', 'funny', 'gauge', 'ghost',
  'giant', 'given', 'glass', 'gleam', 'globe', 'glory', 'glove', 'grace', 'grade', 'grain',
  'grand', 'grant', 'grape', 'graph', 'grasp', 'grass', 'grave', 'great', 'greed', 'green',
  'greet', 'grief', 'grill', 'grind', 'gross', 'group', 'grove', 'grown', 'guard', 'guess',
  'guest', 'guide', 'guilt', 'habit', 'happy', 'harsh', 'haste', 'hasty', 'hatch', 'heart',
  'heavy', 'hedge', 'hello', 'hence', 'honey', 'honor', 'horse', 'hotel', 'house', 'hover',
  'human', 'humor', 'hurry', 'ideal', 'image', 'index', 'inner', 'input', 'issue', 'ivory',
  'japan', 'jeans', 'jelly', 'jewel', 'joint', 'jolly', 'judge', 'juice', 'juicy', 'jumbo',
  'karma', 'kneel', 'knife', 'knock', 'known', 'label', 'labor', 'large', 'laser', 'later',
  'laugh', 'layer', 'learn', 'lease', 'least', 'leave', 'legal', 'lemon', 'level', 'lever',
  'light', 'limit', 'liver', 'local', 'logic', 'loose', 'lorry', 'loser', 'lucky', 'lunar',
  'lunch', 'lying', 'magic', 'major', 'maker', 'maple', 'march', 'match', 'maybe', 'mayor',
  'meant', 'medal', 'media', 'melon', 'mercy', 'merge', 'merit', 'metal', 'meter', 'midst',
  'might', 'minor', 'minus', 'mixed', 'model', 'moist', 'money', 'month', 'moral', 'motor',
  'mount', 'mouse', 'mouth', 'moved', 'movie', 'music', 'naive', 'naked', 'nasty', 'naval',
  'nerve', 'never', 'newly', 'night', 'noble', 'noise', 'north', 'noted', 'novel', 'nurse',
  'occur', 'ocean', 'offer', 'often', 'olive', 'onion', 'onset', 'opera', 'orbit', 'order',
  'organ', 'other', 'ought', 'outer', 'owner', 'paint', 'panel', 'panic', 'paper', 'party',
  'pasta', 'patch', 'pause', 'peace', 'pearl', 'penny', 'phase', 'phone', 'photo', 'piano',
  'piece', 'pilot', 'pinch', 'pitch', 'pixel', 'place', 'plain', 'plane', 'plant', 'plate',
  'plaza', 'plead', 'plot', 'point', 'polar', 'porch', 'pound', 'power', 'press', 'price',
  'pride', 'prime', 'print', 'prior', 'prize', 'proof', 'proud', 'prove', 'pulse', 'punch',
  'pupil', 'puppy', 'purse', 'queen', 'query', 'quest', 'queue', 'quick', 'quiet', 'quite',
  'quota', 'quote', 'radar', 'radio', 'raise', 'rally', 'ranch', 'range', 'rapid', 'ratio',
  'raven', 'reach', 'react', 'ready', 'realm', 'rebel', 'refer', 'relax', 'relay', 'reply',
  'rider', 'ridge', 'rifle', 'right', 'rigid', 'rival', 'river', 'roast', 'robot', 'rocky',
  'roman', 'rough', 'round', 'route', 'royal', 'rugby', 'ruler', 'rumor', 'rural', 'sadly',
  'saint', 'salad', 'sauce', 'scale', 'scare', 'scene', 'scent', 'scope', 'score', 'scout',
  'scrap', 'screw', 'sense', 'serve', 'seven', 'shade', 'shady', 'shaft', 'shake', 'shall',
  'shame', 'shape', 'share', 'shark', 'sharp', 'sheep', 'sheer', 'sheet', 'shelf', 'shell',
  'shift', 'shine', 'shiny', 'shirt', 'shock', 'shoot', 'shore', 'short', 'shout', 'shown',
  'sight', 'silly', 'since', 'sixth', 'sixty', 'skill', 'skirt', 'skull', 'slate', 'sleep',
  'slice', 'slide', 'slope', 'small', 'smart', 'smell', 'smile', 'smoke', 'snake', 'sneak',
  'snout', 'solar', 'solid', 'solve', 'sorry', 'sound', 'south', 'space', 'spare', 'spark',
  'speak', 'spend', 'spent', 'spice', 'spicy', 'spike', 'split', 'spoke', 'sport', 'spray',
  'squad', 'stack', 'staff', 'stage', 'stain', 'stair', 'stake', 'stall', 'stamp', 'stand',
  'stark', 'start', 'state', 'steak', 'steal', 'steam', 'steel', 'steep', 'steer', 'stern',
  'stick', 'stiff', 'still', 'sting', 'stock', 'stone', 'stood', 'stool', 'store', 'storm',
  'story', 'stove', 'strap', 'straw', 'strip', 'stuck', 'study', 'stuff', 'stump', 'style',
  'sugar', 'suite', 'sunny', 'super', 'surge', 'swamp', 'swear', 'sweat', 'sweep', 'sweet',
  'swept', 'swift', 'swing', 'sword', 'table', 'taken', 'taste', 'teach', 'teeth', 'tempo',
  'tenth', 'terry', 'thank', 'theft', 'their', 'theme', 'there', 'these', 'thick', 'thief',
  'thigh', 'thing', 'think', 'third', 'those', 'three', 'threw', 'throw', 'thumb', 'tiger',
  'tight', 'tired', 'title', 'toast', 'today', 'token', 'tooth', 'topic', 'torch', 'total',
  'touch', 'tough', 'tower', 'toxic', 'trace', 'track', 'trade', 'trail', 'train', 'trait',
  'tramp', 'trash', 'tread', 'treat', 'trend', 'trial', 'tribe', 'trick', 'tried', 'troop',
  'truck', 'truly', 'trunk', 'trust', 'truth', 'tulip', 'twice', 'twist', 'ultra', 'uncle',
  'under', 'union', 'unite', 'unity', 'until', 'upper', 'upset', 'urban', 'usage', 'usual',
  'vague', 'valid', 'value', 'vapor', 'vault', 'vinyl', 'viral', 'virus', 'visit', 'vital',
  'vivid', 'vocal', 'voice', 'voter', 'wagon', 'waist', 'waste', 'watch', 'water', 'weary',
  'weave', 'weigh', 'weird', 'whale', 'wheat', 'wheel', 'where', 'which', 'while', 'white',
  'whole', 'whose', 'widen', 'wider', 'width', 'witch', 'woman', 'world', 'worry', 'worse',
  'worst', 'worth', 'would', 'wound', 'wreck', 'wrist', 'write', 'wrong', 'wrote', 'yacht',
  'yield', 'young', 'youth', 'zebra',
];

export const EXTRA_ALLOWED: readonly string[] = [
  'aback', 'abbey', 'abide', 'abled', 'abode', 'acorn', 'acrid', 'adage', 'adept', 'adieu',
  'adobe', 'adore', 'affix', 'afire', 'afoot', 'afoul', 'aged', 'agile', 'aglow', 'aider',
  'aisle', 'algae', 'alibi', 'alien', 'align', 'alley', 'aloft', 'aloof', 'aloud', 'amass',
  'amaze', 'amber', 'amble', 'amend', 'amiss', 'amity', 'ample', 'amply', 'amuse', 'angel',
  'ankle', 'antic', 'anvil', 'aorta', 'aphid', 'apron', 'aptly', 'ardor', 'arose', 'arrow',
  'arson', 'ascot', 'ashen', 'askew', 'atlas', 'atoll', 'atone', 'attic', 'augur', 'aunty',
  'avail', 'avert', 'avian', 'awake', 'awash', 'awful', 'axial', 'axiom', 'azure', 'bacon',
  'badge', 'baggy', 'baler', 'balmy', 'banal', 'banjo', 'barge', 'baron', 'basil', 'baste',
  'batch', 'bathe', 'baton', 'bayou', 'beady', 'beard', 'beast', 'beech', 'befit', 'belch',
  'belie', 'belle', 'belly', 'berry', 'berth', 'beset', 'betel', 'bevel', 'bezel', 'bicep',
  'biddy', 'bigot', 'bilge', 'binge', 'bingo', 'biome', 'birch', 'bison', 'bleak', 'bleat',
  'bleed', 'blimp', 'bloke', 'blond', 'blown', 'bluer', 'bluff', 'blunt', 'blurb', 'blurt',
  'boar', 'bogey', 'boggy', 'bongo', 'booby', 'boozy', 'borax', 'botch', 'bough', 'boule',
  'bowel', 'boxer', 'brace', 'braid', 'brake', 'brash', 'brawl', 'brawn', 'braze', 'brine',
  'briny', 'broil', 'brook', 'broom', 'broth', 'browse', 'brunt', 'buddy', 'budge', 'buggy',
  'bugle', 'bulge', 'bulky', 'bully', 'bumpy', 'burly', 'burnt', 'burro', 'butch', 'butte',
  'buxom', 'byway', 'cacao', 'cache', 'cadet', 'cadre', 'cagey', 'caper', 'carat', 'carol',
  'carve', 'caste', 'cater', 'caulk', 'cease', 'cedar', 'chafe', 'chaff', 'chant', 'chard',
  'cheek', 'cheer', 'chime', 'chirp', 'chock', 'choir', 'choke', 'chord', 'chore', 'chuck',
  'chump', 'chunk', 'churn', 'chute', 'cider', 'cigar', 'cinch', 'circa', 'clack', 'clamp',
  'clang', 'clank', 'clash', 'clasp', 'cleat', 'cleft', 'cloak', 'clove', 'cluck', 'clump',
  'clung', 'coma', 'comet', 'comfy', 'comic', 'conch', 'condo', 'coral', 'corny', 'couch',
  'cough', 'coupe', 'cower', 'coyly', 'cramp', 'crane', 'crank', 'crate', 'crave', 'crawl',
  'craze', 'creak', 'credo', 'creed', 'creek', 'creep', 'creme', 'crepe', 'crept', 'crest',
  'crick', 'croak', 'crock', 'crony', 'crook', 'croon', 'crumb', 'crypt', 'cubic', 'cumin',
  'curio', 'curly', 'curry', 'curse', 'curvy', 'cynic', 'dally', 'dandy', 'datum', 'daunt',
  'dealt', 'debit', 'debug', 'debtor', 'decal', 'decay', 'decor', 'decoy', 'decry', 'deign',
  'deity', 'delta', 'demon', 'demur', 'denim', 'depot', 'derby', 'deter', 'detox', 'deuce',
  'dicey', 'dimly', 'diner', 'dingo', 'dingy', 'diode', 'dirge', 'disco', 'ditto', 'ditty',
  'diver', 'divot', 'dogma', 'doily', 'dolly', 'donut', 'dopey', 'dowdy', 'dowel', 'downy',
  'dowry', 'drake', 'drape', 'drawl', 'drawn', 'dread', 'dross', 'drunk', 'dryer', 'dryly',
  'dually', 'dummy', 'dumpy', 'dunce', 'dusky', 'dusty', 'dutch', 'duvet', 'dwarf', 'dwell',
  'dwelt', 'dying', 'eaten', 'eater', 'ebony', 'eclat', 'edict', 'edify', 'eerie', 'egret',
  'eking', 'elate', 'elegy', 'elfin', 'elude', 'elude', 'email', 'ember', 'emcee', 'endow',
  'enema', 'ennui', 'ensue', 'envoy', 'epoch', 'epoxy', 'equip', 'erase', 'erect', 'erode',
  'erupt', 'ester', 'ethic', 'ethos', 'evade', 'evoke', 'exalt', 'excel', 'exert', 'exile',
  'expel', 'extol', 'exult', 'eying', 'fable', 'facet', 'faded', 'faint', 'fairy', 'faith',
  'farce', 'fatty', 'feign', 'feint', 'fella', 'felon', 'femur', 'feral', 'feral', 'fetal',
  'fetch', 'fetid', 'fetus', 'fiber', 'fibre', 'ficus', 'filet', 'filly', 'filmy', 'filth',
  'finch', 'finer', 'first', 'fishy', 'fjord', 'flail', 'flair', 'flaky', 'flank', 'flare',
  'fleck', 'flick', 'flier', 'fling', 'flint', 'flirt', 'flony', 'flora', 'floss', 'flout',
  'flown', 'fluff', 'flung', 'flunk', 'flute', 'foamy', 'foist', 'folio', 'folly', 'foray',
  'forgo', 'forte', 'foyer', 'freak', 'freed', 'freer', 'frially', 'friar', 'fried', 'frill',
  'frisk', 'fritz', 'frock', 'frond', 'froth', 'frown', 'froze', 'fudge', 'fugue', 'fungi',
  'furor', 'furry', 'fussy', 'fuzzy', 'gaffe', 'gaily', 'gamer', 'gamma', 'gamut', 'gassy',
  'gaudy', 'gaunt', 'gavel', 'gawky', 'gecko', 'geeky', 'genie', 'genre', 'ghoul', 'girly',
  'girth', 'given', 'glade', 'gland', 'glare', 'glaze', 'glean', 'glide', 'glint', 'gloat',
  'gloom', 'gloss', 'glyph', 'gnash', 'gnome', 'godly', 'golem', 'goner', 'goody', 'gooey',
  'goofy', 'goose', 'gorge', 'gouge', 'gourd', 'grade', 'graft', 'grate', 'gravy', 'graze',
  'grimy', 'groan', 'groin', 'groom', 'grope', 'gruel', 'gruff', 'grunt', 'guild', 'guile',
  'guise', 'gully', 'gulps', 'gumbo', 'gummy', 'gunk', 'guppy', 'gusto', 'gusty', 'gutsy',
  'gypsy', 'hairy', 'halve', 'handy', 'hardy', 'harem', 'harpy', 'hasty', 'haunt', 'haven',
  'havoc', 'hazel', 'heady', 'heady', 'heard', 'heath', 'heave', 'hefty', 'heist', 'helix',
  'heron', 'hilly', 'hinge', 'hippo', 'hitch', 'hoard', 'hobby', 'hoist', 'holly', 'homer',
  'homey', 'honk', 'hooch', 'hoody', 'hooky', 'hound', 'howdy', 'hulky', 'humid', 'humph',
  'hunch', 'hunky', 'hurl', 'husky', 'hutch', 'hydro', 'hyena', 'hymen', 'hyper', 'icily',
  'icing', 'idiom', 'idiot', 'idler', 'igloo', 'imbue', 'imply', 'incur', 'inept', 'infer',
  'ingot', 'inlay', 'inlet', 'irate', 'irony', 'islet', 'itchy', 'ivory', 'jaunt', 'jazzy',
  'jerky', 'jetty', 'jiffy', 'jingo', 'jocks', 'joker', 'joust', 'jowls', 'juror', 'kappa',
  'kayak', 'kebab', 'khaki', 'kinky', 'kiosk', 'kitty', 'knack', 'knave', 'knead', 'kneed',
  'kneel', 'knelt', 'knoll', 'koala', 'krill', 'ladle', 'lager', 'lance', 'lanky', 'lapel',
  'lapse', 'larva', 'lasso', 'latch', 'lathe', 'leach', 'leafy', 'leaky', 'leant', 'leapt',
  'ledge', 'leech', 'leery', 'lefty', 'legit', 'lemur', 'levee', 'libel', 'liege', 'lilac',
  'limbo', 'lined', 'linen', 'liner', 'lingo', 'lipid', 'lithe', 'livid', 'llama', 'loamy',
  'loath', 'lobby', 'lofty', 'loined', 'loony', 'loopy', 'louse', 'lousy', 'lowly', 'loyal',
  'lucid', 'lumen', 'lumpy', 'lunge', 'lupus', 'lurch', 'lurid', 'lusty', 'lymph', 'lynch',
  'lyric', 'macaw', 'macho', 'madam', 'madly', 'mafia', 'mango', 'mangy', 'manor', 'mason',
  'matey', 'mauve', 'meaty', 'mecca', 'medic', 'melee', 'meld', 'mends', 'meow', 'mesh',
  'metro', 'micro', 'midge', 'milky', 'mimic', 'mince', 'miner', 'mingle', 'minty', 'miser',
  'mocha', 'modal', 'mogul', 'moldy', 'molar', 'molt', 'moose', 'moped', 'moral', 'moron',
  'morph', 'mossy', 'moth', 'motto', 'mould', 'moult', 'mourn', 'mousy', 'mucky', 'muddy',
  'mulch', 'mummy', 'munch', 'mural', 'murky', 'mushy', 'musky', 'musty', 'muter', 'myrrh',
  'nadir', 'nanny', 'nappy', 'nasal', 'natal', 'nudge', 'ninja', 'nomad', 'nook', 'noose',
  'nosey', 'notch', 'nudge', 'nutty', 'nylon', 'nymph', 'oaken', 'oasis', 'obese', 'oboe',
  'ochre', 'octet', 'odder', 'oddly', 'offal', 'often', 'ombre', 'omega', 'onset', 'ombré',
  'opine', 'optic', 'opium', 'oust', 'ovary', 'overt', 'ovine', 'ovoid', 'ozone', 'paddy',
  'pagan', 'palsy', 'pansy', 'papal', 'parer', 'parka', 'parry', 'parse', 'pasty', 'patio',
  'patty', 'payee', 'payer', 'pecan', 'pedal', 'penal', 'perch', 'peril', 'perky', 'pesky',
  'pesto', 'petal', 'petty', 'pewit', 'phony', 'picky', 'piety', 'piggy', 'piling', 'pinky',
  'piped', 'piper', 'pique', 'pithy', 'plaid', 'plait', 'plank', 'pleat', 'plied', 'plier',
  'pluck', 'plumb', 'plume', 'plump', 'plunk', 'plush', 'poesy', 'poker', 'polka', 'polyp',
  'pooch', 'poppy', 'posit', 'posse', 'pouch', 'pouty', 'prank', 'prawn', 'preen', 'prick',
  'pricy', 'primp', 'privy', 'probe', 'prong', 'prose', 'proxy', 'prude', 'prune', 'psalm',
  'pudgy', 'puffy', 'pukka', 'pulpy', 'pygmy', 'quack', 'quail', 'quaff', 'quake', 'qualm',
  'quark', 'quart', 'quash', 'quasi', 'quell', 'quill', 'quilt', 'quirk', 'rabid', 'racer',
  'radii', 'rajah', 'ralph', 'ramen', 'rared', 'raspy', 'raten', 'rebus', 'rebut', 'recap',
  'recur', 'redux', 'reedy', 'regal', 'rehab', 'reign', 'renew', 'repay', 'repel', 'resin',
  'retch', 'retro', 'retry', 'reuse', 'revel', 'revue', 'rhino', 'rhyme', 'ridge', 'rinse',
  'riper', 'risen', 'risky', 'ritzy', 'roomy', 'roost', 'rotor', 'rouge', 'rouse', 'rowdy',
  'rower', 'ruddy', 'runny', 'runic', 'rusty', 'sable', 'salsa', 'salty', 'salve', 'salvo',
  'sandy', 'saner', 'sappy', 'sassy', 'satin', 'satyr', 'sauna', 'saute', 'savor', 'savoy',
  'savvy', 'scald', 'scaly', 'scamp', 'scant', 'scarf', 'scary', 'scoff', 'scold', 'scone',
  'scoop', 'scorn', 'scour', 'scowl', 'scram', 'scrub', 'scrum', 'seedy', 'sepia', 'serum',
  'sewer', 'shale', 'shalt', 'shank', 'shawl', 'shear', 'sheen', 'shied', 'shill', 'shire',
  'shirk', 'shoal', 'shone', 'shorn', 'shove', 'shovel', 'shred', 'shrew', 'shrub', 'shrug',
  'shuck', 'shunt', 'shush', 'shyly', 'siege', 'sieve', 'silky', 'sinew', 'singe', 'siren',
  'sissy', 'sizer', 'skate', 'skein', 'skied', 'skier', 'skiff', 'skimp', 'skulk', 'slack',
  'slain', 'slang', 'slant', 'sleek', 'sleet', 'slept', 'slink', 'sloop', 'slosh', 'sloth',
  'slump', 'slung', 'slunk', 'slurp', 'slush', 'slyly', 'smack', 'smear', 'smirk', 'smite',
  'smith', 'smock', 'smote', 'smug', 'snack', 'snail', 'snare', 'snarl', 'sniff', 'snipe',
  'snoop', 'snore', 'snort', 'snowy', 'snuck', 'snuff', 'soapy', 'sober', 'soggy', 'sonic',
  'sooth', 'sooty', 'sower', 'spade', 'spank', 'spawn', 'spear', 'speck', 'spell', 'spelt',
  'sperm', 'spiel', 'spill', 'spine', 'spiny', 'spire', 'spite', 'splat', 'spoil', 'spool',
  'spoon', 'spore', 'spout', 'sprig', 'sprit', 'sprue', 'sprung', 'spume', 'spunk', 'spurn',
  'spurt', 'squat', 'squib', 'stade', 'staid', 'stank', 'stave', 'stead', 'stein', 'stilt',
  'stint', 'stoic', 'stoke', 'stomp', 'stony', 'stork', 'stout', 'stowed', 'stray', 'strut',
  'stung', 'stunk', 'stunt', 'suave', 'sully', 'sumac', 'surer', 'surly', 'swami', 'swash',
  'swath', 'swirl', 'swish', 'swoon', 'swoop', 'swore', 'sworn', 'swung', 'synod', 'syrup',
  'tabby', 'taboo', 'tacit', 'tacky', 'taffy', 'taint', 'tally', 'talon', 'tamer', 'tango',
  'tangy', 'taper', 'tapir', 'tardy', 'tarot', 'tarry', 'tatty', 'taunt', 'tawny', 'teary',
  'tease', 'teddy', 'teeth', 'tenet', 'tenor', 'tepee', 'tepid', 'terse', 'testy', 'thane',
  'thong', 'thorn', 'thrall', 'throb', 'throng', 'thump', 'thyme', 'tiara', 'tibia', 'tidal',
  'tilde', 'timer', 'timid', 'tipsy', 'titan', 'tithe', 'toffy', 'togas', 'toile', 'tonal',
  'tonga', 'tonic', 'toots', 'topaz', 'toper', 'torso', 'torus', 'total', 'toter', 'trawl',
  'triad', 'tripe', 'trite', 'troll', 'trope', 'trout', 'trove', 'truce', 'truer', 'tryst',
  'tuber', 'tuck', 'tulle', 'tumor', 'tunic', 'turbo', 'tusk', 'tutor', 'twang', 'tweak',
  'tweed', 'tweet', 'twerp', 'twine', 'twirl', 'twixt', 'tying', 'udder', 'ulcer', 'umbra',
  'unbox', 'unclogged', 'undid', 'undue', 'unfed', 'unfit', 'unify', 'unlit', 'unmet', 'unset',
  'untie', 'unwed', 'unzip', 'upend', 'urine', 'usher', 'usurp', 'uterus', 'vaunt', 'veer',
  'velum', 'venom', 'verge', 'verse', 'verve', 'vicar', 'video', 'vigil', 'vigor', 'villa',
  'visor', 'vista', 'vodka', 'vogue', 'vomit', 'vouch', 'vowel', 'vroom', 'vying', 'wacky',
  'wafer', 'wager', 'waive', 'waltz', 'warty', 'washy', 'watery', 'waver', 'waxen', 'weal',
  'weedy', 'welch', 'welsh', 'wench', 'whack', 'wharf', 'wheat', 'wheel', 'whelp', 'whiff',
  'whine', 'whiny', 'whirl', 'whisk', 'whoop', 'whorl', 'widow', 'wield', 'wight', 'wimpy',
  'wince', 'winch', 'windy', 'wiper', 'wired', 'wispy', 'woken', 'woody', 'wooer', 'woozy',
  'wordy', 'wormy', 'worse', 'woven', 'wrack', 'wrath', 'wreak', 'wrung', 'wryly', 'yearn',
  'yeast', 'yodel', 'yokel', 'yucky', 'yummy', 'zappy', 'zesty', 'zonal',
];

const norm = (list: readonly string[]): string[] =>
  Array.from(new Set(list.map((w) => w.toLowerCase()))).filter((w) => /^[a-z]{5}$/.test(w));

/** Answer pool: common, fair five-letter solutions. */
export const ANSWER_WORDS: readonly string[] = norm(ANSWERS);

/** Every valid guess (answers + extra dictionary words). */
export const VALID_GUESSES: ReadonlySet<string> = new Set([
  ...ANSWER_WORDS,
  ...norm(EXTRA_ALLOWED),
]);

/** Pick a random answer. */
export function randomAnswer(): string {
  return ANSWER_WORDS[Math.floor(Math.random() * ANSWER_WORDS.length)];
}

/** Whether a guess is an accepted dictionary word. */
export function isValidGuess(word: string): boolean {
  return VALID_GUESSES.has(word.toLowerCase());
}
